### ISSUE TITLE
Improve layout of credits

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#1154]
**Author: hikerstk**

The credit layout in the gui is somewhat strict, e.g.:
= name =

text1
text2

Will end up on two screens, instead of one screen. Atm you have to do:
= name =

some-other-text
- text1
- text2

Also a crash can be caused with incorrectly formatted lines, e.g. if you remove 'some-other-text' and only have the lines with -, it will crash with:
#0  0x0000000000767926 in std::vector<irr::core::string<wchar_t, irr::core::irrAllocator<wchar_t> >, std::allocator<irr::core::string<wchar_t, irr::core::irrAllocator<wchar_t> > > >::push_back (this=0xffffffffffffffe8, __x=...) at /usr/include/c++/4.5/bits/stl_vector.h:743
#1  0x000000000092fc4a in CreditsSection::addSubEntry (this=0x1666d760, subEntryString=...)

```
at /home/joerg/local/supertuxkart/supertuxkart/src/states_screens/credits.cpp:71
```
#2  0x000000000092e373 in CreditsScreen::loadedFromFile (this=0x16496b70) at /home/joerg/local/supertuxkart/supertuxkart/src/states_screens/credits.cpp:194
#3  0x00000000007f3bbf in GUIEngine::Screen::loadFromFile (this=0x16496b70) at /home/joerg/local/supertuxkart/supertuxkart/src/guiengine/screen.cpp:133
#4  0x00000000007d543d in GUIEngine::AbstractStateManager::pushScreen (this=0x14499d0, screen=0x16496b70)

```
at /home/joerg/local/supertuxkart/supertuxkart/src/guiengine/abstract_state_manager.cpp:130
```

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/1098

**Comment by Alayan-stk-2** [comment]
The credits should support displaying pictures. Most other games do have some animations or pictures there. We could show concept art, gameplay scenes...
