### ISSUE TITLE
Crash pressing ESC on login screen

### ISSUE THREAD

**Issue by Arthur-D** [supertuxkart/stk-code#1713]
I started the game with "Always show login screen" enabled, and automatic login and upon pressing Escape the game crashed. I would recommend pressing Esc defaults to using last non-online user and bringing you to the main menu. Alternatively, just close the game gracefully.

```
[Thread 0x7fffe991a700 (LWP 25205) exited]
[Thread 0x7fffe36e5700 (LWP 25204) exited]
[info   ] Singleton: Destroyed singleton.
[warn   ] STKHost: Packet logging file has been closed.
[info   ] Singleton: Destroyed singleton.

Program received signal SIGSEGV, Segmentation fault.
irr::gui::CGUIStaticText::~CGUIStaticText (this=this@entry=0x2e315a00, __in_chrg=<optimized out>, __vtt_parm=<optimized out>)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/lib/irrlicht/source/Irrlicht/CGUIStaticText.cpp:47
47                      OverrideFont->drop();
(gdb) bt full
#0  irr::gui::CGUIStaticText::~CGUIStaticText (this=this@entry=0x2e315a00, __in_chrg=<optimized out>, __vtt_parm=<optimized out>)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/lib/irrlicht/source/Irrlicht/CGUIStaticText.cpp:47
No locals.
#1  0x0000000000fb5f59 in irr::gui::CGUIStaticText::~CGUIStaticText (this=0x2e315a00, __in_chrg=<optimized out>, 
    __vtt_parm=<optimized out>)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/lib/irrlicht/source/Irrlicht/CGUIStaticText.cpp:48
No locals.
#2  0x0000000001016c13 in drop (this=<optimized out>)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/lib/irrlicht/include/IReferenceCounted.h:124
        this = <optimized out>
#3  ~IGUIElement (__vtt_parm=<optimized out>, this=0x2d659490, __in_chrg=<optimized out>)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/lib/irrlicht/include/IGUIElement.h:60
        it = {Current = 0x2e315bf0}
#4  ~IGUIButton (__vtt_parm=0x1447c08 <VTT for irr::gui::CGUIButton+8>, this=0x2d659490, __in_chrg=<optimized out>)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/lib/irrlicht/include/IGUIButton.h:58
No locals.
#5  irr::gui::CGUIButton::~CGUIButton (this=this@entry=0x2d659490, __in_chrg=<optimized out>, __vtt_parm=<optimized out>)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/lib/irrlicht/source/Irrlicht/CGUIButton.cpp:44
No locals.
#6  0x0000000001016d19 in irr::gui::CGUIButton::~CGUIButton (this=0x2d659490, __in_chrg=<optimized out>, __vtt_parm=<optimized out>)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/lib/irrlicht/source/Irrlicht/CGUIButton.cpp:57
No locals.
#7  0x00000000009cf20c in irr::IReferenceCounted::drop (this=0x2d659658)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/lib/irrlicht/include/IReferenceCounted.h:124
No locals.
#8  0x00000000009cf827 in irr::gui::IGUIElement::~IGUIElement (this=0x1c7eb28, 
    __vtt_parm=0x1422678 <VTT for irr::gui::CGUIEnvironment+24>, __in_chrg=<optimized out>)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/lib/irrlicht/include/IGUIElement.h:60
        it = {Current = 0x2e315370}
#9  0x0000000000ee25c4 in irr::gui::CGUIEnvironment::~CGUIEnvironment (this=this@entry=0x1c7eb20, __in_chrg=<optimized out>, 
---Type <return> to continue, or q <return> to quit---
    __vtt_parm=<optimized out>)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/lib/irrlicht/source/Irrlicht/CGUIEnvironment.cpp:101
No locals.
#10 0x0000000000ee2629 in irr::gui::CGUIEnvironment::~CGUIEnvironment (this=0x1c7eb20, __in_chrg=<optimized out>, 
    __vtt_parm=<optimized out>)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/lib/irrlicht/source/Irrlicht/CGUIEnvironment.cpp:166
No locals.
#11 0x00000000009cf20c in irr::IReferenceCounted::drop (this=0x1c7ed08)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/lib/irrlicht/include/IReferenceCounted.h:124
No locals.
#12 0x0000000000e9a58b in irr::scene::CSceneManager::~CSceneManager (this=this@entry=0x1c9aff0, __in_chrg=<optimized out>, 
    __vtt_parm=<optimized out>)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/lib/irrlicht/source/Irrlicht/CSceneManager.cpp:341
        i = <optimized out>
#13 0x0000000000e9ab99 in irr::scene::CSceneManager::~CSceneManager (this=0x1c9aff0, __in_chrg=<optimized out>, 
    __vtt_parm=<optimized out>)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/lib/irrlicht/source/Irrlicht/CSceneManager.cpp:374
No locals.
#14 0x0000000000e62a3b in drop (this=<optimized out>)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/lib/irrlicht/include/IReferenceCounted.h:124
        this = <optimized out>
#15 irr::CIrrDeviceLinux::~CIrrDeviceLinux (this=this@entry=0x19445a0, __in_chrg=<optimized out>, __vtt_parm=<optimized out>)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/lib/irrlicht/source/Irrlicht/CIrrDeviceLinux.cpp:161
No locals.
#16 0x0000000000e62ce9 in irr::CIrrDeviceLinux::~CIrrDeviceLinux (this=0x19445a0, __in_chrg=<optimized out>, 
    __vtt_parm=<optimized out>)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/lib/irrlicht/source/Irrlicht/CIrrDeviceLinux.cpp:221
No locals.
#17 0x00000000009cf20c in irr::IReferenceCounted::drop (this=0x19447f8)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/lib/irrlicht/include/IReferenceCounted.h:124
---Type <return> to continue, or q <return> to quit---
No locals.
#18 0x0000000000b8c4d8 in IrrDriver::~IrrDriver (this=0x1943f10, __in_chrg=<optimized out>)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/src/graphics/irr_driver.cpp:147
No locals.
#19 0x0000000000b8c63a in IrrDriver::~IrrDriver (this=0x1943f10, __in_chrg=<optimized out>)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/src/graphics/irr_driver.cpp:153
No locals.
#20 0x0000000000c72c02 in cleanUserConfig () at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/src/main.cpp:1538
No locals.
#21 0x0000000000c72ae1 in cleanSuperTuxKart () at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/src/main.cpp:1515
No locals.
#22 0x0000000000c723b0 in main (argc=1, argv=0x7fffffffdd38) at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/src/main.cpp:1420
No locals.
```

**Comment by Benau** [comment]
Can be closed when using new font rendering engine

**Comment by qwertychouskie** [comment]
> Can be closed when using new font rendering engine

I think you forgot to actually close it. :)

**Comment by Benau** [comment]
New font render engine is used, should be fixed in git
