### ISSUE TITLE
Segfault on Linux building with Clang

### ISSUE THREAD

**Issue by Arthur-D** [supertuxkart/stk-code#1769]
I use Clang on this computer, which may explain why I don't see this crash on my usual desktop machine.

On my Linux Mint 17 computer with AMD 6570 using proprietary driver version 14.301, the game crashes immediately with the following stack trace:

Starting program: /home/magne/SuperTuxKart/supertuxkart-git/stk-code/cmake_build/bin/supertuxkart 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Irrlicht Engine version 1.8.0
Linux 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64
[debug  ] main: Error messages and other text output will be logged to /home/magne/.config/supertuxkart/0.8.2/stdout.log.
[info   ] [FileManager]: Data files will be fetched from: 'data/'
[info   ] [FileManager]: Data files will be fetched from: 'data/../../stk-assets/'
[info   ] [FileManager]: User directory is '/home/magne/.config/supertuxkart/0.8.2/'.
[info   ] [FileManager]: Addons files will be stored in '/home/magne/.local/share/supertuxkart/addons/'.
[info   ] [FileManager]: Screenshots will be stored in '/home/magne/.cache/supertuxkart/screenshots/'.
[info   ] [FileManager]: User-defined grand prix will be stored in '/home/magne/.local/share/supertuxkart/grandprix/'.
[info   ] [FileManager]: Asset 0 will be loaded from 'data/challenges/'.
[info   ] [FileManager]: Asset 1 will be loaded from 'data/fonts/'.
[info   ] [FileManager]: Asset 2 will be loaded from 'data/gfx/'.
[info   ] [FileManager]: Asset 3 will be loaded from 'data/grandprix/'.
[info   ] [FileManager]: Asset 4 will be loaded from 'data/gui/'.
[info   ] [FileManager]: Asset 5 will be loaded from 'data/../../stk-assets/library/'.
[info   ] [FileManager]: Asset 6 will be loaded from 'data/../../stk-assets/models/'.
[info   ] [FileManager]: Asset 7 will be loaded from 'data/../../stk-assets/music/'.
[info   ] [FileManager]: Asset 8 will be loaded from 'data/../../stk-assets/tracks/'.
[info   ] [FileManager]: Asset 9 will be loaded from 'data/../../stk-assets/sfx/'.
[info   ] [FileManager]: Asset 10 will be loaded from 'data/shaders/'.
[info   ] [FileManager]: Asset 11 will be loaded from 'data/skins/'.
[info   ] [FileManager]: Asset 12 will be loaded from 'data/../../stk-assets/textures/'.
[info   ] [FileManager]: Asset 13 will be loaded from 'data/po/'.
[error  ] User Config: Unknown value for verify-peer; expected true or false
[debug  ] translation: Env var LANGUAGE = 'nb_NO.UTF-8'.
[debug  ] translation: Language 'Norwegian Bokmål (Norway)'.
Adding language fallback nb
[info   ] IrrDriver: OpenGL version: 4.3
[info   ] IrrDriver: OpenGL vendor: ATI Technologies Inc.
[info   ] IrrDriver: OpenGL renderer: AMD Radeon HD 6570
[info   ] IrrDriver: OpenGL version string: 4.3.13084 Core Profile/Debug Context 14.301.1001
[info   ] GLDriver: AMD Vertex Shader Layer enabled
[info   ] GLDriver: ARB Buffer Storage enabled
[info   ] GLDriver: ARB Base Instance enabled
[info   ] GLDriver: ARB Draw Indirect enabled
[info   ] GLDriver: ARB Compute Shader enabled
[info   ] GLDriver: ARB Texture Storage enabled
[info   ] GLDriver: ARB Texture View enabled
[warn   ] Graphics: Can not find version for '4.3.13084 Core Profile/Debug Context 14.301.1001' 'AMD Radeon HD 6570' - ignored.
[info   ] irr_driver: GLSL supported.
[info   ] GLWrap: Compiling shader : data/shaders/frustrum.vert
[info   ] GLWrap: Compiling shader : data/shaders/coloredquad.frag
[info   ] GLWrap: Compiling shader : data/shaders/object_pass.vert
[info   ] GLWrap: Compiling shader : data/shaders/coloredquad.frag

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff523e518 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) thread apply all bt full

Thread 1 (Thread 0x7ffff7e9c800 (LWP 3695)):
#0  0x00007ffff523e518 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x00007ffff5e90003 in std::string::compare(std::string const&) const ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#2  0x000000000090041d in std::operator< <char, std::char_traits<char>, std::allocator<char> > (__lhs=..., __rhs=...)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/basic_string.h:2571
No locals.
#3  0x0000000000900031 in std::less<std::string>::operator() (
    this=0x17ab840 <SkinConfig::m_render_params>, __x=..., __y=...)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/stl_function.h:235
No locals.
#4  0x0000000000b49ee1 in std::_Rb_tree<std::string, std::pair<std::string const, GUIEngine::BoxRenderParams>, std::_Select1st<std::pair<std::string const, GUIEngine::BoxRenderParams> >, std::less<std::string>, std::allocator<std::pair<std::string const, GUIEngine::BoxRenderParams> > >::_M_get_insert_hint_unique_pos (
    this=0x17ab840 <SkinConfig::m_render_params>, __position=..., __k=...)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits---Type <return> to continue, or q <return> to quit---
/stl_tree.h:1427
        __pos = {_M_node = 0x1e4e750}
#5  0x0000000000b4afad in std::_Rb_tree<std::string, std::pair<std::string const, GUIEngine::BoxRenderParams>, std::_Select1st<std::pair<std::string const, GUIEngine::BoxRenderParams> >, std::less<std::string>, std::allocator<std::pair<std::string const, GUIEngine::BoxRenderParams> > >::_M_emplace_hint_unique<std::piecewise_construct_t const&, std::tuple<std::string&&>, std::tuple<> >(std::_Rb_tree_const_iterator<std::pair<std::string const, GUIEngine::BoxRenderParams> >, std::piecewise_construct_t const&, std::tuple<std::string&&>&&, std::tuple<>&&) (
    this=0x17ab840 <SkinConfig::m_render_params>, __pos=..., 
    __args=<unknown type in /home/magne/SuperTuxKart/supertuxkart-git/stk-code/cmake_build/bin/supertuxkart, CU 0xcdda29, DIE 0xcfcf2e>, 
    __args=<unknown type in /home/magne/SuperTuxKart/supertuxkart-git/stk-code/cmake_build/bin/supertuxkart, CU 0xcdda29, DIE 0xcfcf2e>, 
    __args=<unknown type in /home/magne/SuperTuxKart/supertuxkart-git/stk-code/cmake_build/bin/supertuxkart, CU 0xcdda29, DIE 0xcfcf2e>)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/stl_tree.h:1673
        __res = {first = 0x7fffffffd7c0, second = 0x7fffffffd5c0}
        __z = 0x1e5cd70
#6  0x0000000000b47e7b in std::map<std::string, GUIEngine::BoxRenderParams, std::less<std::string>, std::allocator<std::pair<std::string const, GUIEngine::BoxRenderParams> > >::operator[](std::string&&) (
---Type <return> to continue, or q <return> to quit---
    this=0x17ab840 <SkinConfig::m_render_params>, 
    __k=<unknown type in /home/magne/SuperTuxKart/supertuxkart-git/stk-code/cmake_build/bin/supertuxkart, CU 0xcdda29, DIE 0xcfcea6>)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/stl_map.h:484
        __i = {_M_node = 0x1e4e750}
#7  0x0000000000b475d0 in SkinConfig::parseElement (node=0x1e3b540)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/src/guiengine/skin.cpp:119
        type = {static npos = 18446744073709551615, 
          _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
            _M_p = 0x1e8c4f8 "achievement-message"}}
        state = {static npos = 18446744073709551615, 
          _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x1e8c0b8 "neutral"}}
        image = {static npos = 18446744073709551615, 
          _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
            _M_p = 0x1e4e8e8 "peach/achievement.png"}}
        leftborder = 128
        rightborder = 13
        topborder = 13
---Type <return> to continue, or q <return> to quit---
        bottomborder = 13
        hborder_out_portion = 0,300000012
        vborder_out_portion = 0
        preserve_h_aspect_ratios = true
        areas = {static npos = 18446744073709551615, 
          _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
            _M_p = 0x7ffff60d93f8 <std::string::_Rep::_S_empty_rep_storage+24> ""}}
        new_param = {m_image = 0x1e50170, m_y_flip_set = false, 
          m_left_border = 128, m_right_border = 13, m_top_border = 13, 
          m_bottom_border = 13, m_preserve_h_aspect_ratios = true, 
          m_hborder_out_portion = 0,300000012, m_vborder_out_portion = 0, 
          m_vertical_flip = false, areas = 31, static BODY = 1, 
          static LEFT = 2, static RIGHT = 4, static TOP = 8, 
          static BOTTOM = 16, m_source_area_left = {UpperLeftCorner = {X = 0, 
              Y = 13}, LowerRightCorner = {X = 128, Y = 115}}, 
          m_source_area_center = {UpperLeftCorner = {X = 128, Y = 13}, 
            LowerRightCorner = {X = 371, Y = 115}}, m_source_area_right = {
            UpperLeftCorner = {X = 371, Y = 13}, LowerRightCorner = {X = 384, 
              Y = 115}}, m_source_area_top = {UpperLeftCorner = {X = 128, 
              Y = 0}, LowerRightCorner = {X = 371, Y = 13}}, 
          m_source_area_bottom = {UpperLeftCorner = {X = 128, Y = 115}, 
---Type <return> to continue, or q <return> to quit---
            LowerRightCorner = {X = 371, Y = 128}}, m_source_area_top_left = {
            UpperLeftCorner = {X = 0, Y = 0}, LowerRightCorner = {X = 128, 
              Y = 13}}, m_source_area_top_right = {UpperLeftCorner = {X = 371, 
              Y = 0}, LowerRightCorner = {X = 384, Y = 13}}, 
          m_source_area_bottom_left = {UpperLeftCorner = {X = 0, Y = 115}, 
            LowerRightCorner = {X = 128, Y = 128}}, 
          m_source_area_bottom_right = {UpperLeftCorner = {X = 371, Y = 115}, 
            LowerRightCorner = {X = 384, Y = 128}}, 
          m_source_area_left_yflip = {UpperLeftCorner = {X = 0, Y = 0}, 
            LowerRightCorner = {X = 0, Y = 0}}, m_source_area_center_yflip = {
            UpperLeftCorner = {X = 0, Y = 0}, LowerRightCorner = {X = 0, 
              Y = 0}}, m_source_area_right_yflip = {UpperLeftCorner = {X = 0, 
              Y = 0}, LowerRightCorner = {X = 0, Y = 0}}, 
          m_source_area_top_yflip = {UpperLeftCorner = {X = 0, Y = 0}, 
            LowerRightCorner = {X = 0, Y = 0}}, m_source_area_bottom_yflip = {
            UpperLeftCorner = {X = 0, Y = 0}, LowerRightCorner = {X = 0, 
              Y = 0}}, m_source_area_top_left_yflip = {UpperLeftCorner = {
              X = 0, Y = 0}, LowerRightCorner = {X = 0, Y = 0}}, 
          m_source_area_top_right_yflip = {UpperLeftCorner = {X = 0, Y = 0}, 
            LowerRightCorner = {X = 0, Y = 0}}, 
          m_source_area_bottom_left_yflip = {UpperLeftCorner = {X = 0, Y = 0}, 
            LowerRightCorner = {X = 0, Y = 0}}, 
          m_source_area_bottom_right_yflip = {UpperLeftCorner = {X = 0, 
---Type <return> to continue, or q <return> to quit---
              Y = 0}, LowerRightCorner = {X = 0, Y = 0}}}
#8  0x0000000000b3a2d5 in SkinConfig::loadFromFile (file=...)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/src/guiengine/skin.cpp:169
        node = 0x1e3b540
        i = 1
        root = 0x1e4d730
        amount = 63
#9  0x0000000000b39e64 in GUIEngine::Skin::Skin (this=0x1e41e70, 
    fallback_skin=0x1d4b850)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/src/guiengine/skin.cpp:297
        skin_name = {static npos = 18446744073709551615, 
          _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
            _M_p = 0x1e2a048 "data/skins/Peach.stkskin"}}
        e = @0x0: <incomplete type>
#10 0x0000000000add5bd in GUIEngine::init (device_a=0x1814b50, driver_a=
    0x1d03940, state_manager=0x1e3c510)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/src/guiengine/engine.cpp:1017
        screen_width = 32767
        screen_height = -169652435
---Type <return> to continue, or q <return> to quit---
        scale = 0
        normal_text_scale = 0
        title_text_scale = 1,86107724e-38
        sfont = 0x7fffffffddb0
        digit_font = 0x1e3c540
        sfont_larger = 0xcabd35
     <std::_Vector_base<StateManager::ActivePlayer*, std::allocator<StateManager::ActivePlayer*> >::_Vector_base()+21>
        sfont_smaller = 0x1e3c540
        sfont2 = 0xcabd5f <std::_Vector_base<StateManager::ActivePlayer*, std::allocator<StateManager::ActivePlayer*> >::_Vector_impl::_Vector_impl()+31>
#11 0x00000000008eba5f in initRest ()
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/src/main.cpp:1060
        device = 0x1814b50
        driver = 0x1d03940
#12 0x00000000008ec60c in main (argc=1, argv=0x7fffffffe468)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/src/main.cpp:1201
        s = {static npos = 18446744073709551615, 
          _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
            _M_p = 0x7ffff60d93f8 <std::string::_Rep::_S_empty_rep_storage+24> ""}}
        materials_file = {static npos = 18446744073709551615, 
---Type <return> to continue, or q <return> to quit---
          _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
            _M_p = 0x1 <error: Cannot access memory at address 0x1>}}
        important_message = {array = 0x0, allocated = 1, used = 0, 
          allocator = {_vptr$irrAllocator = 0x7fff0000007c}}
        e = @0x0: <incomplete type>

**Comment by Arthur-D** [comment]
Using GCC I have no issues; I assume that my clang version might be too old (3.4). Closing until someone can verify (I am happy to use GCC instead).
