### ISSUE TITLE
Crash while searching for users online

### ISSUE THREAD

**Issue by tomreyn** [supertuxkart/stk-code#1981]
While testing cdb35b0804f176048a11f1571d7c0333c191d82b on Ubuntu 14.04 x86_64 I did an online user search:

```
[info   ] HTTPRequest: Sending username=%27%60%22--%3Exxx%3Cyyy%3Ezzz&password=****&save-session=false to https://addons.supertuxkart.net/api/v2/user/connect/
[info   ] HTTPRequest: Sending username=%27%60%22--%3Exxx%3Cyyy%3Ezzz&password=*****************************&save-session=false to https://addons.supertuxkart.net/api/v2/user/connect/
[info   ] HTTPRequest: Sending username=demo&password=********&save-session=false to https://addons.supertuxkart.net/api/v2/user/connect/
[info   ] HTTPRequest: Sending userid=836&token=************************&visitingid=836 to https://addons.supertuxkart.net/api/v2/user/get-friends-list/
[info   ] HTTPRequest: Sending userid=836&token=************************ to https://addons.supertuxkart.net/api/v2/user/poll/
[info   ] HTTPRequest: Sending userid=836&token=************************&search-string=%27%60%22--%3Exxx%3Cyyy%3Ezzz to https://addons.supertuxkart.net/api/v2/user/user-search/
Segmentation fault (core dumped)
```

... and crashed...

```
gdb -batch -ex 'thread apply all bt full' supertuxkart core
[New LWP 12451]
[New LWP 12462]
[New LWP 12454]
[New LWP 12458]
[New LWP 12461]
[New LWP 12460]
[New LWP 12465]
[New LWP 12464]
[New LWP 12452]
[New LWP 12463]
[New LWP 12459]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./supertuxkart'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000009c4069 in OnlineUserSearch::eventCallback (this=0x1a977a50, widget=0x1a96eb00, name=..., player_id=0) at /home/tomreyn/SCM/stk-code/src/states_screens/online_user_search.cpp:230
230	        new UserInfoDialog(m_users[m_selected_index]);

Thread 11 (Thread 0x7ff1e3713700 (LWP 12459)):
#0  0x00007ff1f5181b9d in nanosleep () at ../sysdeps/unix/syscall-template.S:81
No locals.
#1  0x00007ff1f4ad654a in ?? () from /usr/lib/x86_64-linux-gnu/libopenal.so.1
No symbol table info available.
#2  0x00007ff1f4ae35eb in ?? () from /usr/lib/x86_64-linux-gnu/libopenal.so.1
No symbol table info available.
#3  0x00007ff1f4ad5e6a in ?? () from /usr/lib/x86_64-linux-gnu/libopenal.so.1
No symbol table info available.
#4  0x00007ff1f517a182 in start_thread (arg=0x7ff1e3713700) at pthread_create.c:312
        __res = <optimized out>
        pd = 0x7ff1e3713700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140676879693568, -3762923930731127532, 0, 0, 140676879694272, 140676879693568, 3757319842960792852, 3757271683395640596}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#5  0x00007ff1f2b1c00d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.

Thread 10 (Thread 0x7ff1cf7fd700 (LWP 12463)):
#0  0x00007ff1f2ae2acd in nanosleep () at ../sysdeps/unix/syscall-template.S:81
No locals.
#1  0x00007ff1f2b14034 in usleep (useconds=<optimized out>) at ../sysdeps/unix/sysv/linux/usleep.c:32
        ts = {tv_sec = 0, tv_nsec = 1000000}
#2  0x0000000000917049 in StkTime::sleep (msec=1) at /home/tomreyn/SCM/stk-code/src/utils/time.hpp:117
No locals.
#3  0x0000000000c6bc0a in SFXManager::mainLoop (obj=0x3632b90) at /home/tomreyn/SCM/stk-code/src/audio/sfx_manager.cpp:367
        empty = false
        current = 0x0
        me = 0x3632b90
#4  0x00007ff1f517a182 in start_thread (arg=0x7ff1cf7fd700) at pthread_create.c:312
        __res = <optimized out>
        pd = 0x7ff1cf7fd700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140676545107712, -3762923930731127532, 0, 0, 140676545108416, 140676545107712, 3757398884317682964, 3757271683395640596}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#5  0x00007ff1f2b1c00d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.

Thread 9 (Thread 0x7ff1e7433700 (LWP 12452)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
No locals.
#1  0x00007ff1ea344b73 in cnd_wait (mtx=0x2bb9208, cond=0x2bb9230) at ../../../../../../../include/c11/threads_posix.h:154
No locals.
#2  pipe_semaphore_wait (sema=0x2bb9208) at ../../../../../../../src/gallium/auxiliary/os/os_thread.h:248
No locals.
#3  radeon_drm_cs_emit_ioctl (param=param@entry=0x2bb8ef0) at ../../../../../../../src/gallium/winsys/radeon/drm/radeon_drm_winsys.c:594
        ws = 0x2bb8ef0
        cs = <optimized out>
        i = <optimized out>
#4  0x00007ff1ea344417 in impl_thrd_routine (p=<optimized out>) at ../../../../../../../include/c11/threads_posix.h:87
        pack = {func = 0x7ff1ea344a40 <radeon_drm_cs_emit_ioctl>, arg = 0x2bb8ef0}
#5  0x00007ff1f517a182 in start_thread (arg=0x7ff1e7433700) at pthread_create.c:312
        __res = <optimized out>
        pd = 0x7ff1e7433700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140676943787776, -3762923930731127532, 0, 0, 140676943788480, 140676943787776, 3757310617371041044, 3757271683395640596}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#6  0x00007ff1f2b1c00d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.

Thread 8 (Thread 0x7ff1e47d9700 (LWP 12464)):
#0  0x00007ff1f2b13933 in select () at ../sysdeps/unix/syscall-template.S:81
No locals.
#1  0x0000000000da6c45 in enet_socket_wait (socket=12, condition=0x7ff1e47d8dac, timeout=20) at /home/tomreyn/SCM/stk-code/lib/enet/unix.c:423
        readSet = {__fds_bits = {4096, 0 <repeats 15 times>}}
        writeSet = {__fds_bits = {0 <repeats 16 times>}}
        timeVal = {tv_sec = 0, tv_usec = 15942}
        selectCount = 0
#2  0x0000000000da62a2 in enet_host_service (host=0x19b9fc00, event=0x7ff1e47d8df0, timeout=2172844039) at /home/tomreyn/SCM/stk-code/lib/enet/protocol.c:1821
        waitCondition = 2
#3  0x0000000000ca1cd0 in STKHost::receive_data (self=0x184ad7a0) at /home/tomreyn/SCM/stk-code/src/network/stk_host.cpp:87
        event = {type = ENET_EVENT_TYPE_NONE, peer = 0x0, channelID = 76 'L', data = 0, packet = 0x0}
        myself = 0x184ad7a0
        host = 0x19b9fc00
#4  0x00007ff1f517a182 in start_thread (arg=0x7ff1e47d9700) at pthread_create.c:312
        __res = <optimized out>
        pd = 0x7ff1e47d9700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140676897281792, -3762923930731127532, 0, 0, 140676897282496, 140676897281792, 3757304341350079764, 3757271683395640596}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#5  0x00007ff1f2b1c00d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.

Thread 7 (Thread 0x7ff1cd2fc700 (LWP 12465)):
#0  0x00007ff1f2ae2acd in nanosleep () at ../sysdeps/unix/syscall-template.S:81
No locals.
#1  0x00007ff1f2b14034 in usleep (useconds=<optimized out>) at ../sysdeps/unix/sysv/linux/usleep.c:32
        ts = {tv_sec = 0, tv_nsec = 2000000}
#2  0x0000000000917049 in StkTime::sleep (msec=2) at /home/tomreyn/SCM/stk-code/src/utils/time.hpp:117
No locals.
#3  0x0000000000c9bdf7 in protocolManagerAsynchronousUpdate (data=0x19b7eea0) at /home/tomreyn/SCM/stk-code/src/network/protocol_manager.cpp:48
        manager = 0x19b7eea0
#4  0x00007ff1f517a182 in start_thread (arg=0x7ff1cd2fc700) at pthread_create.c:312
        __res = <optimized out>
        pd = 0x7ff1cd2fc700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140676506306304, -3762923930731127532, 0, 0, 140676506307008, 140676506306304, 3757394896977419540, 3757271683395640596}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#5  0x00007ff1f2b1c00d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.

Thread 6 (Thread 0x7ff1e1374700 (LWP 12460)):
#0  0x00007ff1f3006b42 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
No symbol table info available.
#1  0x00007ff1f300535e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
No symbol table info available.
#2  0x00007ff1f517a182 in start_thread (arg=0x7ff1e1374700) at pthread_create.c:312
        __res = <optimized out>
        pd = 0x7ff1e1374700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140676842342144, -3762923930731127532, 0, 0, 140676842342848, 140676842342144, 3757315942593617172, 3757271683395640596}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#3  0x00007ff1f2b1c00d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.

Thread 5 (Thread 0x7ff1e0b73700 (LWP 12461)):
#0  0x00007ff1f3006b42 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
No symbol table info available.
#1  0x00007ff1f300535e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
No symbol table info available.
#2  0x00007ff1f517a182 in start_thread (arg=0x7ff1e0b73700) at pthread_create.c:312
        __res = <optimized out>
        pd = 0x7ff1e0b73700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140676833949440, -3762923930731127532, 0, 0, 140676833950144, 140676833949440, 3757314843618860308, 3757271683395640596}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#3  0x00007ff1f2b1c00d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.

Thread 4 (Thread 0x7ff1e1d7b700 (LWP 12458)):
#0  0x00007ff1f2b0ecbd in poll () at ../sysdeps/unix/syscall-template.S:81
No locals.
#1  0x00007ff1e3dc0031 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
No symbol table info available.
#2  0x00007ff1e3db183c in pa_mainloop_poll () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
No symbol table info available.
#3  0x00007ff1e3db1ece in pa_mainloop_iterate () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
No symbol table info available.
#4  0x00007ff1e3db1f80 in pa_mainloop_run () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
No symbol table info available.
#5  0x00007ff1e3dbffe3 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
No symbol table info available.
#6  0x00007ff1e3963f08 in ?? () from /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-4.0.so
No symbol table info available.
#7  0x00007ff1f517a182 in start_thread (arg=0x7ff1e1d7b700) at pthread_create.c:312
        __res = <optimized out>
        pd = 0x7ff1e1d7b700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140676852856576, -3762923930731127532, 0, 0, 140676852857280, 140676852856576, 3757316213713427732, 3757271683395640596}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#8  0x00007ff1f2b1c00d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.

Thread 3 (Thread 0x7ff1e4fda700 (LWP 12454)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
No locals.
#1  0x0000000000b898b0 in Online::RequestManager::mainLoop (obj=0x359f6e0) at /home/tomreyn/SCM/stk-code/src/online/request_manager.cpp:203
        empty = true
        me = 0x359f6e0
#2  0x00007ff1f517a182 in start_thread (arg=0x7ff1e4fda700) at pthread_create.c:312
        __res = <optimized out>
        pd = 0x7ff1e4fda700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140676905674496, -3762923930731127532, 0, 0, 140676905675200, 140676905674496, 3757305440324836628, 3757271683395640596}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#3  0x00007ff1f2b1c00d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.

Thread 2 (Thread 0x7ff1cfffe700 (LWP 12462)):
#0  0x00007ff1f3006b42 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
No symbol table info available.
#1  0x00007ff1f300535e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
No symbol table info available.
#2  0x00007ff1f517a182 in start_thread (arg=0x7ff1cfffe700) at pthread_create.c:312
        __res = <optimized out>
        pd = 0x7ff1cfffe700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140676553500416, -3762923930731127532, 0, 0, 140676553501120, 140676553500416, 3757399983292439828, 3757271683395640596}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#3  0x00007ff1f2b1c00d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.

Thread 1 (Thread 0x7ff1f5561800 (LWP 12451)):
#0  0x00000000009c4069 in OnlineUserSearch::eventCallback (this=0x1a977a50, widget=0x1a96eb00, name=..., player_id=0) at /home/tomreyn/SCM/stk-code/src/states_screens/online_user_search.cpp:230
No locals.
#1  0x0000000000c2dd6b in GUIEngine::EventHandler::sendEventToUser (this=0x34ee190, widget=0x1a96eb00, name=..., playerID=0) at /home/tomreyn/SCM/stk-code/src/guiengine/event_handler.cpp:528
No locals.
#2  0x0000000000c2e043 in GUIEngine::EventHandler::onWidgetActivated (this=0x34ee190, w=0x1a96eb00, playerID=0) at /home/tomreyn/SCM/stk-code/src/guiengine/event_handler.cpp:578
        id = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x1a981f18 "user_list"}}
        parent = 0x0
        __PRETTY_FUNCTION__ = "GUIEngine::EventPropagation GUIEngine::EventHandler::onWidgetActivated(GUIEngine::Widget*, int)"
#3  0x0000000000c2e1e0 in GUIEngine::EventHandler::onGUIEvent (this=0x34ee190, event=...) at /home/tomreyn/SCM/stk-code/src/guiengine/event_handler.cpp:613
        w = 0x1a96eb00
        id = 103
        __PRETTY_FUNCTION__ = "GUIEngine::EventPropagation GUIEngine::EventHandler::onGUIEvent(const irr::SEvent&)"
#4  0x0000000000c2d045 in GUIEngine::EventHandler::OnEvent (this=0x34ee190, event=...) at /home/tomreyn/SCM/stk-code/src/guiengine/event_handler.cpp:149
No locals.
#5  0x0000000000c47e83 in irr::gui::CGUISTKListBox::selectNew (this=0x1a93be60, ypos=536, onlyHover=false) at /home/tomreyn/SCM/stk-code/src/guiengine/widgets/CGUISTKListBox.cpp:419
        event = {EventType = irr::EET_GUI_EVENT, {GUIEvent = {Caller = 0x1a93be60, Element = 0x0, EventType = irr::gui::EGET_LISTBOX_SELECTED_AGAIN}, MouseInput = {X = 445890144, Y = 0, Wheel = 0, Shift = false, Control = false, ButtonStates = 9, Event = 32753}, KeyInput = {Char = 445890144 L'\x1a93be60', Key = 0, PressedDown = false, Shift = false, Control = false}, JoystickEvent = {ButtonStates = 445890144, Axis = {0, 0, 0, 0, 0, 0, 9, 0, 32753, 0, -21200, 14843, 32767, 0, -16720, 6803, 0, 0, -21248, 14843, 32767, 0, -24825, 196, 0, 0, -21200, 14843, 32767, 0, -16800, 6803}, POV = 0, Joystick = 0 '\000'}, LogEvent = {Text = 0x1a93be60 " \356%\001", Level = irr::ELL_DEBUG}, UserEvent = {UserData1 = 445890144, UserData2 = 0}}}
        now = 1423807018
        oldSelected = -1
        eventType = irr::gui::EGET_LISTBOX_SELECTED_AGAIN
#6  0x0000000000c47cbb in irr::gui::CGUISTKListBox::OnEvent (this=0x1a93be60, event=...) at /home/tomreyn/SCM/stk-code/src/guiengine/widgets/CGUISTKListBox.cpp:367
        p = {X = 1191, Y = 536}
#7  0x0000000000ed206f in irr::gui::CGUIEnvironment::postEventFromUser (this=0x2c9e570, event=...) at /home/tomreyn/SCM/stk-code/lib/irrlicht/source/Irrlicht/CGUIEnvironment.cpp:577
No locals.
#8  0x0000000000e7d079 in irr::CIrrDeviceStub::postEventFromUser (this=0x2b95d20, event=...) at /home/tomreyn/SCM/stk-code/lib/irrlicht/source/Irrlicht/CIrrDeviceStub.cpp:227
        absorbed = <optimized out>
        inputReceiver = <optimized out>
#9  0x0000000000e73bc1 in irr::CIrrDeviceLinux::run (this=0x2b95d20) at /home/tomreyn/SCM/stk-code/lib/irrlicht/source/Irrlicht/CIrrDeviceLinux.cpp:1273
        event = {type = 5, xany = {type = 5, serial = 100710, send_event = 0, display = 0x2b7b110, window = 83886082}, xkey = {type = 5, serial = 100710, send_event = 0, display = 0x2b7b110, window = 83886082, root = 698, subwindow = 0, time = 44362982, x = 1191, y = 536, x_root = 1192, y_root = 594, state = 256, keycode = 1, same_screen = 1}, xbutton = {type = 5, serial = 100710, send_event = 0, display = 0x2b7b110, window = 83886082, root = 698, subwindow = 0, time = 44362982, x = 1191, y = 536, x_root = 1192, y_root = 594, state = 256, button = 1, same_screen = 1}, xmotion = {type = 5, serial = 100710, send_event = 0, display = 0x2b7b110, window = 83886082, root = 698, subwindow = 0, time = 44362982, x = 1191, y = 536, x_root = 1192, y_root = 594, state = 256, is_hint = 1 '\001', same_screen = 1}, xcrossing = {type = 5, serial = 100710, send_event = 0, display = 0x2b7b110, window = 83886082, root = 698, subwindow = 0, time = 44362982, x = 1191, y = 536, x_root = 1192, y_root = 594, mode = 256, detail = 1, same_screen = 1, focus = 0, state = 0}, xfocus = {type = 5, serial = 100710, send_event = 0, display = 0x2b7b110, window = 83886082, mode = 698, detail = 0}, xexpose = {type = 5, serial = 100710, send_event = 0, display = 0x2b7b110, window = 83886082, x = 698, y = 0, width = 0, height = 0, count = 44362982}, xgraphicsexpose = {type = 5, serial = 100710, send_event = 0, display = 0x2b7b110, drawable = 83886082, x = 698, y = 0, width = 0, height = 0, count = 44362982, major_code = 0, minor_code = 1191}, xnoexpose = {type = 5, serial = 100710, send_event = 0, display = 0x2b7b110, drawable = 83886082, major_code = 698, minor_code = 0}, xvisibility = {type = 5, serial = 100710, send_event = 0, display = 0x2b7b110, window = 83886082, state = 698}, xcreatewindow = {type = 5, serial = 100710, send_event = 0, display = 0x2b7b110, parent = 83886082, window = 698, x = 0, y = 0, width = 44362982, height = 0, border_width = 1191, override_redirect = 536}, xdestroywindow = {type = 5, serial = 100710, send_event = 0, display = 0x2b7b110, event = 83886082, window = 698}, xunmap = {type = 5, serial = 100710, send_event = 0, display = 0x2b7b110, event = 83886082, window = 698, from_configure = 0}, xmap = {type = 5, serial = 100710, send_event = 0, display = 0x2b7b110, event = 83886082, window = 698, override_redirect = 0}, xmaprequest = {type = 5, serial = 100710, send_event = 0, display = 0x2b7b110, parent = 83886082, window = 698}, xreparent = {type = 5, serial = 100710, send_event = 0, display = 0x2b7b110, event = 83886082, window = 698, parent = 0, x = 44362982, y = 0, override_redirect = 1191}, xconfigure = {type = 5, serial = 100710, send_event = 0, display = 0x2b7b110, event = 83886082, window = 698, x = 0, y = 0, width = 44362982, height = 0, border_width = 1191, above = 2551210575016, override_redirect = 256}, xgravity = {type = 5, serial = 100710, send_event = 0, display = 0x2b7b110, event = 83886082, window = 698, x = 0, y = 0}, xresizerequest = {type = 5, serial = 100710, send_event = 0, display = 0x2b7b110, window = 83886082, width = 698, height = 0}, xconfigurerequest = {type = 5, serial = 100710, send_event = 0, display = 0x2b7b110, parent = 83886082, window = 698, x = 0, y = 0, width = 44362982, height = 0, border_width = 1191, above = 2551210575016, detail = 256, value_mask = 1}, xcirculate = {type = 5, serial = 100710, send_event = 0, display = 0x2b7b110, event = 83886082, window = 698, place = 0}, xcirculaterequest = {type = 5, serial = 100710, send_event = 0, display = 0x2b7b110, parent = 83886082, window = 698, place = 0}, xproperty = {type = 5, serial = 100710, send_event = 0, display = 0x2b7b110, window = 83886082, atom = 698, time = 0, state = 44362982}, xselectionclear = {type = 5, serial = 100710, send_event = 0, display = 0x2b7b110, window = 83886082, selection = 698, time = 0}, xselectionrequest = {type = 5, serial = 100710, send_event = 0, display = 0x2b7b110, owner = 83886082, requestor = 698, selection = 0, target = 44362982, property = 2302102471847, time = 2551210575016}, xselection = {type = 5, serial = 100710, send_event = 0, display = 0x2b7b110, requestor = 83886082, selection = 698, target = 0, property = 44362982, time = 2302102471847}, xcolormap = {type = 5, serial = 100710, send_event = 0, display = 0x2b7b110, window = 83886082, colormap = 698, c_new = 0, state = 0}, xclient = {type = 5, serial = 100710, send_event = 0, display = 0x2b7b110, window = 83886082, message_type = 698, format = 0, data = {b = "\346\354\244\002\000\000\000\000\247\004\000\000\030\002\000\000\250\004\000", s = {-4890, 676, 0, 0, 1191, 0, 536, 0, 1192, 0}, l = {44362982, 2302102471847, 2551210575016, 4294967552, 1}}}, xmapping = {type = 5, serial = 100710, send_event = 0, display = 0x2b7b110, window = 83886082, request = 698, first_keycode = 0, count = 0}, xerror = {type = 5, display = 0x18966, resourceid = 0, serial = 45592848, error_code = 2 '\002', request_code = 0 '\000', minor_code = 0 '\000'}, xkeymap = {type = 5, serial = 100710, send_event = 0, display = 0x2b7b110, window = 83886082, key_vector = "\272\002", '\000' <repeats 14 times>, "\346\354\244\002\000\000\000\000\247\004\000\000\030\002\000"}, xgeneric = {type = 5, serial = 100710, send_event = 0, display = 0x2b7b110, extension = 83886082, evtype = 0}, xcookie = {type = 5, serial = 100710, send_event = 0, display = 0x2b7b110, extension = 83886082, evtype = 0, cookie = 698, data = 0x0}, pad = {140673063845893, 100710, 0, 45592848, 83886082, 698, 0, 44362982, 2302102471847, 2551210575016, 4294967552, 1, 0 <repeats 12 times>}}
        irrevent = {EventType = irr::EET_MOUSE_INPUT_EVENT, {GUIEvent = {Caller = 0x218000004a7, Element = 0x7ffc39fbae80, EventType = irr::gui::EGET_ELEMENT_FOCUS_LOST}, MouseInput = {X = 1191, Y = 536, Wheel = 0.000480044633, Shift = false, Control = false, ButtonStates = 0, Event = irr::EMIE_LMOUSE_LEFT_UP}, KeyInput = {Char = 1191 L'ҧ', Key = 536, PressedDown = false, Shift = false, Control = false}, JoystickEvent = {ButtonStates = 1191, Axis = {536, 0, -20864, 14843, 32764, 0, 0, 0, 3, 0, -20864, 14843, 32767, 0, -20520, 14843, 32767, 0, -12848, 6803, 0, 0, 56, 0, 0, 0, -20800, 14843, 32767, 0, -2400, 145}, POV = 0, Joystick = 0 '\000'}, LogEvent = {Text = 0x218000004a7 <error: Cannot access memory at address 0x218000004a7>, Level = 972795520}, UserEvent = {UserData1 = 1191, UserData2 = 536}}}
#10 0x0000000000ab5d61 in IrrDriver::update (this=0x2b953d0, dt=0.0280000009) at /home/tomreyn/SCM/stk-code/src/graphics/irr_driver.cpp:2053
        world = 0x403914c000000000
#11 0x0000000000ce70d8 in MainLoop::run (this=0x37620e0) at /home/tomreyn/SCM/stk-code/src/main_loop.cpp:151
        dt = 0.0280000009
        device = 0x2b95d20
#12 0x0000000000915422 in main (argc=1, argv=0x7fff39fbb388) at /home/tomreyn/SCM/stk-code/src/main.cpp:1401
        s = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7ff1f38153f8 <std::string::_Rep::_S_empty_rep_storage+24> ""}}
        materials_file = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x184ab048 "../../data/../../stk-assets/models/materials.xml"}}
        important_message = {array = 0x19f3ca60 L"", allocated = 1, used = 1, allocator = {_vptr.irrAllocator = 0x10982d0 <vtable for irr::core::irrAllocator<wchar_t>+16>}}
```

**Comment by auriamg** [comment]
Fixed in git, thanks
