### ISSUE TITLE
Crash in irr::video::CNullDriver::addMaterialRenderer

### ISSUE THREAD

**Issue by konstin** [supertuxkart/stk-code#2100]
## Backtrace
```
(gdb) bt full
#0  irr::video::CNullDriver::addMaterialRenderer (this=0x1c9c040, renderer=0x14, name=0xe43190 <irr::video::COpenGLDriver::queryFeature(irr::video::E_VIDEO_DRIVER_FEATURE) const> "Hcƀ\274\aC\005") at /home/konsti/stk/lib/irrlicht/source/Irrlicht/CNullDriver.cpp:1760
        r = {Name = {array = 0x1c9df40 "Hcƀ\274\aC\005", allocated = 9, used = 9, allocator = {_vptr.irrAllocator = 0x1174eb0 <vtable for irr::core::irrAllocator<char>+16>}}, Renderer = 0x14}
#1  0x0000000000ef3356 in irr::video::COpenGLParallaxMapRenderer::COpenGLParallaxMapRenderer (this=0x1c9d8e0, driver=0x1c9c040, outMaterialTypeNr=@0x7fffffffdb74: 0, baseMaterial=<optimized out>, __in_chrg=<optimized out>, __vtt_parm=<optimized out>) at /home/konsti/stk/lib/irrlicht/source/Irrlicht/COpenGLParallaxMapRenderer.cpp:217
        renderer = <optimized out>
#2  0x0000000000e869e1 in irr::video::COpenGLDriver::createMaterialRenderers (this=0x1c9c040) at /home/konsti/stk/lib/irrlicht/source/Irrlicht/COpenGLDriver.cpp:888
        lmr = <optimized out>
        tmp = 0
        renderer = 0x0
#3  0x0000000000e8b818 in irr::video::COpenGLDriver::genericDriverInit (this=0x1c9c040) at /home/konsti/stk/lib/irrlicht/source/Irrlicht/COpenGLDriver.cpp:833
        vendor = 0x1c9dcc0 ""
#4  0x0000000000e8c5d9 in initDriver (device=0x199ed80, this=0x1c9c040) at /home/konsti/stk/lib/irrlicht/source/Irrlicht/COpenGLDriver.cpp:669
No locals.
#5  irr::video::createOpenGLDriver (params=..., io=0x18c5a90, device=device@entry=0x199ed80) at /home/konsti/stk/lib/irrlicht/source/Irrlicht/COpenGLDriver.cpp:4893
        ogl = 0x1c9c040
#6  0x0000000000ed805d in irr::CIrrDeviceLinux::createDriver (this=0x199ed80) at /home/konsti/stk/lib/irrlicht/source/Irrlicht/CIrrDeviceLinux.cpp:1106
        this = 0x199ed80
#7  0x0000000000edead9 in irr::CIrrDeviceLinux::CIrrDeviceLinux (this=0x199ed80, param=..., __in_chrg=<optimized out>, __vtt_parm=<optimized out>) at /home/konsti/stk/lib/irrlicht/source/Irrlicht/CIrrDeviceLinux.cpp:132
        linuxversion = {array = 0x191f390 "Linux 3.16.0-34-generic #47-Ubuntu SMP Fri Apr 10 18:02:58 UTC 2015 x86_64", allocated = 75, used = 75, allocator = {_vptr.irrAllocator = 0x1174eb0 <vtable for irr::core::irrAllocator<char>+16>}}
        LinuxInfo = {sysname = "Linux\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000", nodename = "Ubuntu-13-04\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000", release = "3.16.0-34-generic\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000", version = "#47-Ubuntu SMP Fri Apr 10 18:02:58 UTC 2015\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000", machine = "x86_64\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000", domainname = "(none)\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"}
#8  0x0000000000e7fdc8 in irr::createDeviceEx (params=...) at /home/konsti/stk/lib/irrlicht/source/Irrlicht/Irrlicht.cpp:89
        dev = 0x0
#9  0x0000000000ae96f0 in IrrDriver::initDevice (this=0x199e430) at /home/konsti/stk/src/graphics/irr_driver.cpp:440
        bits = 32
        modes = 0x199edf8
        ssize = {Width = 1920, Height = 1080}
        res = {Width = 1280, Height = 720}
        params = {DeviceType = irr::EIDT_BEST, DriverType = irr::video::EDT_OPENGL, WindowSize = {Width = 1280, Height = 720}, Bits = 32 ' ', ZBufferBits = 16 '\020', Fullscreen = false, Stencilbuffer = false, Vsync = false, AntiAlias = 0 '\000', HandleSRGB = false, WithAlphaChannel = false, Doublebuffer = true, IgnoreInput = false, Stereobuffer = false, HighPrecisionFPU = false, EventReceiver = 0x199e430, FileSystem = 0x18c5a90, WindowId = 0x0, LoggingLevel = irr::ELL_INFORMATION, DisplayAdapter = 0, DriverMultithreaded = false, UsePerformanceTimer = true, ForceLegacyDevice = false, SDK_version_do_not_use = 0x12154de "1.8.0"}
        material2D = @0x7ffff53cc1b2: {TextureLayer = {{Texture = 0x740000387e7b3d83, TextureWrapU = 15 '\017', TextureWrapV = 0 '\000', BilinearFilter = false, TrilinearFilter = false, AnisotropicFilter = 255 '\377', LODBias = 13 '\r', MatrixAllocator = {_vptr.irrAllocator = 0xceb000000f1850f}, TextureMatrix = 0x850f003844f00dff}, {Texture = 0x24446348000000e3, TextureWrapU = 12 '\f', TextureWrapV = 0 '\000', BilinearFilter = false, TrilinearFilter = false, AnisotropicFilter = 131 '\203', LODBias = -60 '\304', MatrixAllocator = {_vptr.irrAllocator = 0xec8148003844d93d}, TextureMatrix = 0xcc61de800000080}, {Texture = 0x80c4814800, TextureWrapU = 9 '\t', TextureWrapV = 14 '\016', BilinearFilter = false, TrilinearFilter = false, AnisotropicFilter = 254 '\376', LODBias = -1 '\377', MatrixAllocator = {_vptr.irrAllocator = 0x80ec8148003844ba}, TextureMatrix = 0xcc62ee8000000}, {Texture = 0xe900000080c48148, TextureWrapU = 7 '\a', TextureWrapV = 3 '\003', BilinearFilter = false, TrilinearFilter = true, AnisotropicFilter = 255 '\377', LODBias = -1 '\377', MatrixAllocator = {_vptr.irrAllocator = 0x80ec8148003844}, TextureMatrix = 0x48000cc5dfe80000}, {Texture = 0x57e900000080c481, TextureWrapU = 14 '\016', TextureWrapV = 15 '\017', BilinearFilter = true, TrilinearFilter = true, AnisotropicFilter = 255 '\377', LODBias = 72 'H', MatrixAllocator = {_vptr.irrAllocator = 0x80ec81480038}, TextureMatrix = 0x8148000cc5f0e800}, {Texture = 0xfe77e900000080c4, TextureWrapU = 15 '\017', TextureWrapV = 15 '\017', BilinearFilter = true, TrilinearFilter = true, AnisotropicFilter = 72 'H', LODBias = -115 '\215', MatrixAllocator = {_vptr.irrAllocator = 0x80ec814800}, TextureMatrix = 0xc48148000cc5a1e8}, {Texture = 0xfffea6e900000080, TextureWrapU = 15 '\017', TextureWrapV = 15 '\017', BilinearFilter = false, TrilinearFilter = false, AnisotropicFilter = 141 '\215', LODBias = 61 '=', MatrixAllocator = {_vptr.irrAllocator = 0xe800000080ec8148}, TextureMatrix = 0x80c48148000cc5b2}, {Texture = 0xfffffed0e9000000, TextureWrapU = 8 '\b', TextureWrapV = 4 '\004', BilinearFilter = true, TrilinearFilter = false, AnisotropicFilter = 61 '=', LODBias = 31 '\037', MatrixAllocator = {_vptr.irrAllocator = 0x63e800000080ec81}, TextureMatrix = 0x80c48148000cc5}}, MaterialType = 3907584000, AmbientColor = {color = 1224736766}, DiffuseColor = {color = 1140866445}, EmissiveColor = {color = 2168979512}, SpecularColor = {color = 33004}, Shininess = -3918.5, MaterialTypeParam = -3.67342321e-38, MaterialTypeParam2 = 4.61924026e-41, Thickness = -1.69416858e+38, ZBuffer = 255 '\377', AntiAliasing = 255 '\377', ColorMask = 15 '\017', ColorMaterial = 0 '\000', BlendOperation = 14, PolygonOffsetFactor = 3 '\003', PolygonOffsetDirection = irr::video::EPO_BACK, Wireframe = false, PointCloud = false, GouraudShading = false, Lighting = true, ZWriteEnable = false, BackfaceCulling = false, FrontfaceCulling = false, FogEnable = false, NormalizeNormals = true, UseMipMaps = false}
#10 0x0000000000bfb941 in initRest () at /home/konsti/stk/src/main.cpp:1093
        device = 0x0
        driver = 0x92c6f8 <_start>
#11 0x0000000000bfc371 in main (argc=1, argv=0x7fffffffe298) at /home/konsti/stk/src/main.cpp:1255
        s = ""
        materials_file = <error reading variable: Cannot access memory at address 0xffffffffffffffe8>
        important_message = {array = 0x1812508 L"", allocated = 4114397481, used = 32767, allocator = {_vptr.irrAllocator = 0x119}}
```

## Graphics Settings
it crashes even at lowest settings, but just for the record:
```
    <GFX
        anim_gfx="false"
        christmas-mode="0"
        weather_gfx="false"
        steering_animations="0"
        anisotropic="0"
        trilinear="false"
        vsync="false"
        motionblur_enabled="false"
        mlaa="false"
        ssao="false"
        shadows="0"
    >
    </GFX>
```

## Hardware & Plattform
NVidia GeForce GTX 750 Ti with nvidia-340 drivers on ubuntu 14.10. My glxinfo can be found [here](https://gist.github.com/konstin/110c4f6dd7f3e22493a6)

**Comment by deveee** [comment]
Thanks for the backtrace.

Does it crash every time? In fullscreen/windowed mode etc.

Also could you try to run it with default settings?
```
export HOME=./.config
./build/bin/supertuxkart
```
Maybe there is remembered unexpected window widht/height or so...

**Comment by konstin** [comment]
I just discovered that it only crashes when I compile using the clion IDE, though I've got no idea why. 

> Does it crash every time? In fullscreen/windowed mode etc.

It always opens a window with the right size, but the window is filled with the content of the window that was behind STK when it opened. So the STK window normally looks like that:

![bildschirmfoto vom 2015-04-26 11 47 27](https://cloud.githubusercontent.com/assets/6826232/7336668/0bc9ffe4-ec0a-11e4-8c44-e12143af14e8.png)

> Also could you try to run it with default settings?

I've tried that but it doesn't work either.

**Comment by hiker** [comment]
Since this appears IDE related, there's not much we can do about that. Potential reason if you start within clion is that it could restrict e.g. memory usage, or it could use some compiler flags that cause a bug (e.g. incorrect optimisations, or compiler bug).
