### ISSUE TITLE
Crash when selecting a different GP after pressing reload on a random GP

### ISSUE THREAD

**Issue by konstin** [supertuxkart/stk-code#2260]
## Steps to reproduce
 1. Go to the track selection screen
 2. Select random GP -> press reload
 3. Select a different GP
 4. STK crashes

## Log + Callback
```
[...]
[warn   ] EventHandler: While loading screenshot in track screen for last track 'olivermath':
[warn   ] Irrlicht: Could not open file of texture: /home/konsti/.local/share/supertuxkart/addons/tracks/31_valley/screenshot.jpg
[error  ] irr_driver: While loading screenshot in track screen for last track 'olivermath':
[error  ] irr_driver: Texture '/home/konsti/.local/share/supertuxkart/addons/tracks/31_valley/screenshot.jpg' not found.
[error  ] icon_button: Texture '/home/konsti/.local/share/supertuxkart/addons/tracks/31_valley/screenshot.jpg' not found!

supertuxkart: /home/konsti/stk/src/utils/ptr_vector.hpp:85: TYPE* PtrVector<TYPE, type>::get(int) [with TYPE = GUIEngine::Widget; VECTOR_TYPE type = (VECTOR_TYPE)1u]: Zusicherung >>(unsigned int)ID < (unsigned int)m_contents_vector.size()<< nicht erf?llt.
[New Thread 0x7fffae06b700 (LWP 5610)]
[New Thread 0x7fffd6b68700 (LWP 5609)]
[New Thread 0x7fffcc077700 (LWP 5607)]
[New Thread 0x7fffcdc64700 (LWP 5606)]
[New Thread 0x7fffd47f8700 (LWP 5605)]
[New Thread 0x7fffd5979700 (LWP 5604)]
[New Thread 0x7fffd3487700 (LWP 5603)]
[New Thread 0x7fffd3181700 (LWP 5602)]
[New Thread 0x7fffe4d3e700 (LWP 5597)]

Program received signal SIGABRT, Aborted.
0x00007ffff44fa267 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
55	../sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  0x00007ffff44fa267 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007ffff44fbeca in __GI_abort () at abort.c:89
#2  0x00007ffff44f303d in __assert_fail_base (fmt=0x62100004a458 "%s%s%s:%u: %s%sZusicherung >>%s<< nicht erf?llt.\n%n", 
    assertion=assertion@entry=0x167d520 "(unsigned int)ID < (unsigned int)m_contents_vector.size()", 
    file=file@entry=0x167d4c0 "/home/konsti/stk/src/utils/ptr_vector.hpp", line=line@entry=85, 
    function=function@entry=0x1680e00 <PtrVector<GUIEngine::Widget, (VECTOR_TYPE)1>::get(int)::__PRETTY_FUNCTION__> "TYPE* PtrVector<TYPE, type>::get(int) [with TYPE = GUIEngine::Widget; VECTOR_TYPE type = (VECTOR_TYPE)1u]") at assert.c:92
#3  0x00007ffff44f30f2 in __GI___assert_fail (assertion=0x167d520 "(unsigned int)ID < (unsigned int)m_contents_vector.size()", 
    file=0x167d4c0 "/home/konsti/stk/src/utils/ptr_vector.hpp", line=85, 
    function=0x1680e00 <PtrVector<GUIEngine::Widget, (VECTOR_TYPE)1>::get(int)::__PRETTY_FUNCTION__> "TYPE* PtrVector<TYPE, type>::get(int) [with TYPE = GUIEngine::Widget; VECTOR_TYPE type = (VECTOR_TYPE)1u]") at assert.c:101
#4  0x0000000000acbb39 in PtrVector<GUIEngine::Widget, (VECTOR_TYPE)1>::get (this=0x617000148c20, ID=1)
    at /home/konsti/stk/src/utils/ptr_vector.hpp:85
#5  0x0000000000b71fec in GUIEngine::RibbonWidget::focused (this=0x617000148980, playerID=0)
    at /home/konsti/stk/src/guiengine/widgets/ribbon_widget.cpp:563
#6  0x0000000000acef5f in GUIEngine::Widget::setFocusForPlayer (this=0x617000148980, playerID=0)
    at /home/konsti/stk/src/guiengine/widget.cpp:254
#7  0x000000000102e473 in GPInfoScreen::init (this=0x6120001555c0) at /home/konsti/stk/src/states_screens/gp_info_screen.cpp:256
#8  0x0000000000ae2ad5 in GUIEngine::AbstractStateManager::pushScreen (this=0x60700001eda0, screen=0x6120001555c0)
    at /home/konsti/stk/src/guiengine/abstract_state_manager.cpp:134
#9  0x0000000000b9dc93 in GUIEngine::Screen::push (this=0x6120001555c0) at /home/konsti/stk/src/guiengine/screen.cpp:103
#10 0x000000000109ea9d in TracksScreen::eventCallback (this=0x60f000025750, widget=0x618000089c80, name="gps", playerID=0)
    at /home/konsti/stk/src/states_screens/tracks_screen.cpp:116
#11 0x0000000000ae0507 in GUIEngine::EventHandler::sendEventToUser (this=0x6030000ae7f0, widget=0x618000089c80, name="gps", 
    playerID=0) at /home/konsti/stk/src/guiengine/event_handler.cpp:528
#12 0x0000000000ae0a10 in GUIEngine::EventHandler::onWidgetActivated (this=0x6030000ae7f0, w=0x61700017b200, playerID=0)
    at /home/konsti/stk/src/guiengine/event_handler.cpp:568
#13 0x0000000000ae0ed6 in GUIEngine::EventHandler::onGUIEvent (this=0x6030000ae7f0, event=...)
    at /home/konsti/stk/src/guiengine/event_handler.cpp:613
#14 0x0000000000adeb15 in GUIEngine::EventHandler::OnEvent (this=0x6030000ae7f0, event=...)
    at /home/konsti/stk/src/guiengine/event_handler.cpp:149
#15 0x00000000013efff6 in irr::gui::CGUIButton::OnEvent (this=0x615000066d80, event=...)
    at /home/konsti/stk/lib/irrlicht/source/Irrlicht/CGUIButton.cpp:225
#16 0x00000000013f02aa in irr::gui::CGUIButton::OnEvent (this=0x615000065980, event=...)
    at /home/konsti/stk/lib/irrlicht/source/Irrlicht/CGUIButton.cpp:215
#17 0x000000000131502d in irr::gui::CGUIEnvironment::postEventFromUser (this=0x6160001aaf80, event=...)
    at /home/konsti/stk/lib/irrlicht/source/Irrlicht/CGUIEnvironment.cpp:570
#18 0x00000000012a95aa in irr::CIrrDeviceStub::postEventFromUser (this=0x6160001e2480, event=...)
    at /home/konsti/stk/lib/irrlicht/source/Irrlicht/CIrrDeviceStub.cpp:227
#19 0x00000000012a15df in irr::CIrrDeviceLinux::run (this=0x6160001e2480)
    at /home/konsti/stk/lib/irrlicht/source/Irrlicht/CIrrDeviceLinux.cpp:1271
---Type <return> to continue, or q <return> to quit---
#20 0x0000000000ca3611 in IrrDriver::update (this=0x619000020880, dt=0,0329999998)
    at /home/konsti/stk/src/graphics/irr_driver.cpp:2103
#21 0x0000000000f0d290 in MainLoop::run (this=0x6030001fe8b0) at /home/konsti/stk/src/main_loop.cpp:150
#22 0x0000000000ec7f0e in main (argc=1, argv=0x7fffffffde58) at /home/konsti/stk/src/main.cpp:1512
```

**Comment by cap44** [comment]
Cannot reproduce on my end, is this the latest master?

**Comment by konstin** [comment]
yes it is

**Comment by cap44** [comment]
Can't reproduce on my end, STK loads the random grand prix fine for me.

**Comment by konstin** [comment]
It crashes after you select a different GP than the random one.
