### ISSUE TITLE
Crash when starting tutorial

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2278]
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff5868cb9 in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
(gdb) bt full
#0  0x00007ffff5868cb9 in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
No symbol table info available.
#1  0x00007ffff586a1f3 in _Unwind_RaiseException ()
   from /lib/x86_64-linux-gnu/libgcc_s.so.1
No symbol table info available.
#2  0x00007ffff5fee13c in __cxa_throw ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#3  0x0000000000aea0ed in utf8::next<char const*> (
    it=@0x7fffffffd1c8: 0x7fff92730c09 "\363ra", end=0x7fff92730c0c "")
    at /home/Dokumenty/linux/supertuxkart-git/src/utils/utf8/checked.h:149
        cp = 0
        err_code = utf8::internal::INCOMPLETE_SEQUENCE
#4  0x0000000000ae9681 in utf8::utf8to16<std::back_insert_iterator<std::vector<wchar_t, std::allocator<wchar_t> > >, char const*> (
    start=0x7fff92730c09 "\363ra", end=0x7fff92730c0c "", result=...)
    at /home/Dokumenty/linux/supertuxkart-git/src/utils/utf8/checked.h:237
        cp = 71
#5  0x0000000000ae884b in StringUtils::utf8_to_wide (
    input=0x7fff92730c08 "G\363ra")
    at /home/Dokumenty/linux/supertuxkart-git/src/utils/string_utils.cpp:707
        utf16line = std::vector of length 1, capacity 64 = {71 L'G'}
---Type <return> to continue, or q <return> to quit---
#6  0x0000000000d8b0a8 in Scripting::GUI::translate (
    formatString=0x7fff8e254ff8, arg1=0x7fff8e255000, arg2=0x7fff8e255008, 
    arg3=0x7fff8e255010)
    at /home/Dokumenty/linux/supertuxkart-git/src/scriptengine/script_gui.cpp:111
        out = {
          array = 0x7fff9b8c2db0 L"Accelerate with <%s>, and steer with <%s> and <%s>.", allocated = 52, used = 52, allocator = {
            _vptr.irrAllocator = 0x11f64b0 <vtable for irr::core::irrAllocator<wchar_t>+16>}}
#7  0x0000000000d8b2ce in Scripting::GUI::proxy_translateAndInsertValues3 (
    formatString=0x7fff8e254ff8, arg1=0x7fff8e255000, arg2=0x7fff8e255008, 
    arg3=0x7fff8e255010)
    at /home/Dokumenty/linux/supertuxkart-git/src/scriptengine/script_gui.cpp:145
No locals.
#8  0x000000000116ff63 in endstack ()
    at /home/Dokumenty/linux/supertuxkart-git/lib/angelscript/source/as_callfunc_x64_gcc.cpp:154
        retQW1 = 140735803042855
#9  0x0000000000d8b293 in Scripting::GUI::proxy_translateAndInsertValues2 (
    formatString=0x7fffde4c5080, arg1=0x40, arg2=
---Type <return> to continue, or q <return> to quit---
    0x115ee81 <asCBuilder::GetNameSpaceFromNode(asCScriptNode*, asCScriptCode*, asSNameSpace*, asCScriptNode**)+121>)
    at /home/Dokumenty/linux/supertuxkart-git/src/scriptengine/script_gui.cpp:140
No locals.
#10 0x000000008e263e00 in ?? ()
No symbol table info available.
#11 0x00007fffffffd690 in ?? ()
No symbol table info available.
#12 0x0000000000000000 in ?? ()
No symbol table info available.
```

**Comment by auriamg** [comment]
There appears to be an invalid UTF-8 string. I cannot reproduce it, perhaps it is related to a specific language or key configuration?

**Comment by deveee** [comment]
It seems that it doesn't like non-ascii chars in arg1, arg2, arg3 parameters. Some of them causes crashes (for example 'ó' caused crash for me), some of them are simply not displayed, for example 'ą'. But this only affects args, which are put into string where are <%s> .

Maybe there is something wrong with utf8_to_wide function. I don't have more time to look at this today.

**Comment by deveee** [comment]
Works for me now. Thanks!
