### ISSUE TITLE
Crash with add-on track "Cocoa Temple (light)"

### ISSUE THREAD

**Issue by Arthur-D** [supertuxkart/stk-code#2631]
Upon starting the add-on "Cocoa Temple (light)", the game crashed. I used the add-on Wilber kart, with all karts selected, however I do not think this influenced it. While there probably is something malformed in the track causing this, the game should ignore it, print an error/warning and at the very least not crash.
It is reproducible for me.
Backtrace:
```
[error  ] EventHandler: While loading track '/home/magne/.local/share/supertuxkart/addons/tracks/cocoa-temple--light-/track.xml'
[error  ] Irrlicht: Could not load mesh, file format seems to be unsupported: /home/magne/.local/share/supertuxkart/addons/tracks/cocoa-temple--light-/
[error  ] irr_driver: Cannot load mesh </home/magne/.local/share/supertuxkart/addons/tracks/cocoa-temple--light-/>

[error  ] track: Object model '/home/magne/.local/share/supertuxkart/addons/tracks/cocoa-temple--light-/' not found, ignored.

[warn   ] Animations: Expected 'curve' for animation, got 'static-object' --> Ignored.
[warn   ] Animations: Expected 'curve' for animation, got 'static-object' --> Ignored.
supertuxkart: /home/magne/SuperTuxKart/supertuxkart-git/stk-code/src/animations/ipo.cpp:469: void Ipo::update(float, Vec3*, Vec3*, Vec3*): Assertion `false' failed.

Thread 1 "supertuxkart" received signal SIGABRT, Aborted.
0x00007ffff512c418 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54      ../sysdeps/unix/sysv/linux/raise.c: Fila eller mappa finnes ikke.
(gdb) thread apply all bt full

Thread 12 (Thread 0x7fffe6021700 (LWP 8270)):
#0  0x00007ffff51c28dd in nanosleep () at ../sysdeps/unix/syscall-template.S:84
No locals.
#1  0x00007ffff51f44d4 in usleep (useconds=<optimized out>) at ../sysdeps/posix/usleep.c:32
        ts = {tv_sec = 0, tv_nsec = 1000000}
#2  0x0000000000a420da in StkTime::sleep (msec=1)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/src/utils/time.hpp:120
No locals.
#3  0x0000000000a96b12 in SFXManager::mainLoop (obj=0x323f6f0)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/src/audio/sfx_manager.cpp:398
        t = 76238.566000000006
        empty = false
        current = 0x0
        me = 0x323f6f0
#4  0x00007ffff7bc16fa in start_thread (arg=0x7fffe6021700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fffe6021700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737052284672, -3010172624969083601, 0, 140737488346335, 
                8388608, 140736817348160, 3010229698062767407, 3010190751031547183}, mask_was_saved = 0}}, 
          priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#5  0x00007ffff51fdb5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.

Thread 11 (Thread 0x7fffd6740700 (LWP 8269)):
---Type <return> to continue, or q <return> to quit---
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:143
No locals.
#1  0x00007fffe4fe87e8 in pa_threaded_mainloop_wait () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
No symbol table info available.
#2  0x00007ffff751aa69 in ?? () from /usr/lib/x86_64-linux-gnu/libopenal.so.1
No symbol table info available.
#3  0x00007ffff751df27 in ?? () from /usr/lib/x86_64-linux-gnu/libopenal.so.1
No symbol table info available.
#4  0x00007ffff7bc16fa in start_thread (arg=0x7fffd6740700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fffd6740700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736791316224, -3010172624969083601, 0, 140737488346111, 
                140736791316928, 140737342712048, 3010123181263213871, 3010190751031547183}, 
              mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, 
              canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#5  0x00007ffff51fdb5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.

Thread 10 (Thread 0x7fffd6f41700 (LWP 8268)):
#0  0x00007ffff51f1e8d in poll () at ../sysdeps/unix/syscall-template.S:84
No locals.
#1  0x00007fffe4fe8201 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
No symbol table info available.
#2  0x00007fffe4fd9a01 in pa_mainloop_poll () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
No symbol table info available.
---Type <return> to continue, or q <return> to quit---
#3  0x00007fffe4fda0ae in pa_mainloop_iterate () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
No symbol table info available.
#4  0x00007fffe4fda160 in pa_mainloop_run () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
No symbol table info available.
#5  0x00007fffe4fe8149 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
No symbol table info available.
#6  0x00007fffe4b80678 in ?? () from /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-8.0.so
No symbol table info available.
#7  0x00007ffff7bc16fa in start_thread (arg=0x7fffd6f41700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fffd6f41700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736799708928, -3010172624969083601, 0, 140737488346127, 
                8388608, 52368240, 3010122100542068015, 3010190751031547183}, mask_was_saved = 0}}, priv = {
            pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#8  0x00007ffff51fdb5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.

Thread 5 (Thread 0x7fffe9c29700 (LWP 8263)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
No locals.
#1  0x0000000000c550b6 in Online::RequestManager::mainLoop (obj=0x31e2270)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/src/online/request_manager.cpp:206
        empty = true
        me = 0x31e2270
#2  0x00007ffff7bc16fa in start_thread (arg=0x7fffe9c29700) at pthread_create.c:333
---Type <return> to continue, or q <return> to quit---
        __res = <optimized out>
        pd = 0x7fffe9c29700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737115232000, -3010172624969083601, 0, 140737488346367, 
                140737115232704, 0, 3010203863834481967, 3010190751031547183}, mask_was_saved = 0}}, priv = {
            pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#3  0x00007ffff51fdb5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.

Thread 4 (Thread 0x7fffeb066700 (LWP 8262)):
#0  0x00007ffff56e7b4f in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
No symbol table info available.
#1  0x00007ffff56e5418 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
No symbol table info available.
#2  0x00007ffff7bc16fa in start_thread (arg=0x7fffeb066700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fffeb066700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737136453376, -3010172624969083601, 0, 140737488344383, 
                140737136454080, 3, 3010201146730796335, 3010190751031547183}, mask_was_saved = 0}}, priv = {
            pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
---Type <return> to continue, or q <return> to quit---
#3  0x00007ffff51fdb5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.

Thread 3 (Thread 0x7fffeb867700 (LWP 8261)):
#0  0x00007ffff56e7b4f in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
No symbol table info available.
#1  0x00007ffff56e5418 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
No symbol table info available.
#2  0x00007ffff7bc16fa in start_thread (arg=0x7fffeb867700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fffeb867700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737144846080, -3010172624969083601, 0, 140737488344383, 
                140737144846784, 2, 3010200048829781295, 3010190751031547183}, mask_was_saved = 0}}, priv = {
            pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#3  0x00007ffff51fdb5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.

Thread 2 (Thread 0x7fffec068700 (LWP 8260)):
#0  0x00007ffff56e7b4f in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
No symbol table info available.
#1  0x00007ffff56e5418 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
No symbol table info available.
#2  0x00007ffff7bc16fa in start_thread (arg=0x7fffec068700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fffec068700
---Type <return> to continue, or q <return> to quit---
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737153238784, -3010172624969083601, 0, 140737488344383, 
                140737153239488, 1, 3010216540967327023, 3010190751031547183}, mask_was_saved = 0}}, priv = {
            pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#3  0x00007ffff51fdb5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.

Thread 1 (Thread 0x7ffff7fa47c0 (LWP 8256)):
#0  0x00007ffff512c418 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
        resultvar = 0
        pid = 8256
        selftid = 8256
#1  0x00007ffff512e01a in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x4, sa_sigaction = 0x4}, sa_mask = {__val = {140737488345216, 
              27614107, 140737488345296, 0, 140737354055680, 19963071, 469, 19963488, 0, 0, 140737305356988, 
              140737306454568, 140737306468208, 13835058055282163712, 140737306454568, 19963071}}, 
          sa_flags = -134299648, sa_restorer = 0x1309cbf}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007ffff5124bd7 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x1309cbf "false", 
    file=file@entry=0x1309c58 "/home/magne/SuperTuxKart/supertuxkart-git/stk-code/src/animations/ipo.cpp", 
    line=line@entry=469, 
    function=function@entry=0x1309e60 <Ipo::update(float, Vec3*, Vec3*, Vec3*)::__PRETTY_FUNCTION__> "void Ipo::update(float, Vec3*, Vec3*, Vec3*)") at assert.c:92
        str = 0x7fffa0e9a850 "x\253K\365\377\177"
        total = 4096
---Type <return> to continue, or q <return> to quit---
#3  0x00007ffff5124c82 in __GI___assert_fail (assertion=0x1309cbf "false", 
    file=0x1309c58 "/home/magne/SuperTuxKart/supertuxkart-git/stk-code/src/animations/ipo.cpp", line=469, 
    function=0x1309e60 <Ipo::update(float, Vec3*, Vec3*, Vec3*)::__PRETTY_FUNCTION__> "void Ipo::update(float, Vec3*, Vec3*, Vec3*)") at assert.c:101
No locals.
#4  0x0000000000ab3ddf in Ipo::update (this=0x7fff83758ae0, time=0.0500000007, xyz=0x7fffffffdaf0, 
    hpr=0x7fff8320290c, scale=0x7fffffffdb00)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/src/animations/ipo.cpp:469
        __PRETTY_FUNCTION__ = "void Ipo::update(float, Vec3*, Vec3*, Vec3*)"
#5  0x0000000000ab10a0 in AnimationBase::update (this=0x7fff832028b0, dt=0.0500000007, xyz=0x7fffffffdaf0, 
    hpr=0x7fff8320290c, scale=0x7fffffffdb00)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/src/animations/animation_base.cpp:106
        _foreach_i = 0
        __PRETTY_FUNCTION__ = "virtual void AnimationBase::update(float, Vec3*, Vec3*, Vec3*)"
        curr = 0x7fff83758ae0
#6  0x0000000000ab4ed7 in ThreeDAnimation::update (this=0x7fff832028b0, dt=0.0500000007)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/src/animations/three_d_animation.cpp:84
        xyz = {<btVector3> = {m_floats = {-54.2400017, -1.91999996, -117.82, 0}}, <No data fields>}
        m = {M = {-nan(0x7fdc80), 4.59163468e-41, 2.85827864e-38, 0, -2.64818234e-17, 4.59163468e-41, 
            -3.61577189e-19, -4.87968058e-14, 3.21278726e-38, 0, -2.60390633e-17, 4.59163468e-41, 3.03790297e-38, 
            0, -nan(0x7fe2d0), 4.59163468e-41}}
        my = {M = {0, 0, -5.32824519e+32, 4.59163468e-41, -2.64818234e-17, 4.59163468e-41, -3.61577189e-19, 
            -4.87968058e-14, -2.64818234e-17, 4.59163468e-41, 0, 0, -nan(0x7fdbe0), 4.59163468e-41, 
            -5.32824519e+32, 4.59163468e-41}}
        scale = {<btVector3> = {m_floats = {1, 1, 1, 0}}, <No data fields>}
        mx = {M = {-nan(0x7fdc10), 4.59163468e-41, 1.53892629e-38, 0, 1.40129846e-45, 0, -nan(0x7fdcc0), 
            4.59163468e-41, -nan(0x7fdca0), 4.59163468e-41, -nan(0x7fdc80), 4.59163468e-41, 1.2751816e-43, 0, 
            -2.64817969e-17, 4.59163468e-41}}
        mz = {M = {-nan(0x7fdbe0), 4.59163468e-41, 1.68155816e-44, 0, 1.83143553e+25, 1.80626929e+28, 
            -nan(0x7fdc40), 4.59163468e-41, -nan(0x7fdc10), 4.59163468e-41, 1.47449081e-38, 0, -1.37557717e-12, 
            4.59163468e-41, -nan(0x7fdc40), 4.59163468e-41}}
---Type <return> to continue, or q <return> to quit---
        hpr = {X = 0, Y = 0, Z = 0}
        __PRETTY_FUNCTION__ = "virtual void ThreeDAnimation::update(float)"
#7  0x0000000000da859e in TrackObject::update (this=0x7fff81299d10, dt=0.0500000007)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/src/tracks/track_object.cpp:467
No locals.
#8  0x0000000000da4dbf in TrackObjectManager::update (this=0x27013550, dt=0.0500000007)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/src/tracks/track_object_manager.cpp:149
        _foreach_i = 1
        curr = 0x7fff81299d10
#9  0x0000000000ddc6d5 in Track::update (this=0x7fff8c7bb170, dt=0.0500000007)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/src/tracks/track.cpp:1434
No locals.
#10 0x0000000000c0e4c7 in World::updateTrack (this=0x7fff79f94c90, dt=0.0500000007)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/src/modes/world.cpp:1062
No locals.
#11 0x0000000000bf5ce8 in LinearWorld::update (this=0x7fff79f94c90, dt=0.0500000007)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/src/modes/linear_world.cpp:196
        kart_amount = 6
        pos_used = std::vector of length -35184365154524, capacity -20 = {0, 1064304640, 0, -1074790400, 1, 0, 
          -8552, 32767, 11, 0, -1596624896, -1453604125, 0, 0, 0, 0, -8496, 32767, 12456456, 0, 1028443341, 
          1028443341, 150632064, 0, -8432, 32767, 12456748, 0, 27633680, 1028443341, 150632064, 0, -16711681, 
          32767, 10635190, 1028443341, 28064416, 0, -1596624896, -1453604125, -7696, 32767, 14633548, 0, -7464, 
          32767, 12900950, 2, 27865392, 0, 27865648, 0, 27865424, 0, 27865392, 0, 27865424, 0, 27080360, 0, 
          -8288, 32767, -179590288, 32767, -8272, 32767, 8273, -32768, -8273, 32767, 43, 0, -8192, 32767, -7464, 
          32767, 8209, -32768, -8209, 32767, 8193, -32768, -8193, 32767, 1, 0, 4, 49, 0, 0, -179590368, 32767, 
          -179590368, 32767, 1056, 0, 2, 0, 17, 0, -1681469936, 32767, 1, 1, 19697560, 0, 1040, 0, 27633680, 0, 
          1, 1, 19697560, 0, 27476888, 0, -8112, 32767, 0, 0, 7936, -32768, -8033, 32767, -8080, 32767, 6, 0, 
          1869753645, 29807, 0, 0, -8048, 32767, 8, 0, 1953705261, 1953853284, 0, 124, 956859744, 0, 17, 0, 17, 
          0, 22362201, 0, -7984, 32767, 12, 0, 1600746855, 1801678700, 1735290926, 32512, -7952, 32767, 0, 0, 
          27571712, 0, -171381128, 32767, 34374176, 0, 29, 0, 29, 0, 27080360, 1, -1626976928, 32767, 42, 0, 58, 
          0, -7464, 32767, -7856, 32767, 13, 0, 1702125933, 1818323314, 1836592755, 108, -7824, 32767, 8, 0, 
---Type <return> to continue, or q <return> to quit---
          1952868711, 1735290926, -182999808, 32767, -7792, 32767, 10, 0...}
#12 0x0000000000c0dbc4 in World::updateWorld (this=0x7fff79f94c90, dt=0.0500000007)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/src/modes/world.cpp:884
        __PRETTY_FUNCTION__ = "void World::updateWorld(float)"
#13 0x0000000000be1208 in MainLoop::updateRace (this=0x8fa7680, dt=0.0500000007)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/src/main_loop.cpp:133
No locals.
#14 0x0000000000be132c in MainLoop::run (this=0x8fa7680)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/src/main_loop.cpp:154
        dt = 0.0500000007
        device = 0x1ac3aa0
#15 0x0000000000df4a4c in main (argc=2, argv=0x7fffffffe2d8)
    at /home/magne/SuperTuxKart/supertuxkart-git/stk-code/src/main.cpp:1682
        s = ""
        materials_file = "data/../../stk-assets/models/materials.xml"
        important_message = {array = 0x7fff9bc6ce10 L"", allocated = 1, used = 1, allocator = {
            _vptr.irrAllocator = 0x12c8f98 <vtable for irr::core::irrAllocator<wchar_t>+16>}}
```

**Comment by qwertychouskie** [comment]
That was actually my fault, fixed version uploaded to add-ons.  That's what I get for hard-coding scene.xml. :)
