### ISSUE TITLE
Crash on startup in kart model

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2751]
I get following crash on startup in current git version
```
Program received signal SIGSEGV, Segmentation fault.
0x0000000100aba5c4 in irr::core::aabbox3d<float>::addInternalPoint (this=0x601c818c4, p=...) at /cygdrive/d/deve/stk-code/lib/irrlicht/include/aabbox3d.h:76
76                              addInternalPoint(p.X, p.Y, p.Z);
(gdb) bt
#0  0x0000000100aba5c4 in irr::core::aabbox3d<float>::addInternalPoint (this=0x601c818c4, p=...) at /cygdrive/d/deve/stk-code/lib/irrlicht/include/aabbox3d.h:76
#1  0x0000000100ae4601 in irr::scene::SSkinMeshBuffer::recalculateBoundingBox (this=<optimized out>) at /cygdrive/d/deve/stk-code/lib/irrlicht/include/SSkinMeshBuffer.h:187
#2  0x00000001007a88bf in irr::scene::CSkinnedMesh::updateBoundingBox (this=this@entry=0x600931220) at /cygdrive/d/deve/stk-code/lib/irrlicht/source/Irrlicht/CSkinnedMesh.cpp:1180
#3  0x00000001007acd56 in irr::scene::CSkinnedMesh::updateBoundingBox (this=0x600931220) at /cygdrive/d/deve/stk-code/lib/irrlicht/source/Irrlicht/CSkinnedMesh.cpp:1170
#4  irr::scene::CSkinnedMesh::animateMesh (blend=1, frame=20, this=0x600931220) at /cygdrive/d/deve/stk-code/lib/irrlicht/source/Irrlicht/CSkinnedMesh.cpp:165
#5  irr::scene::CSkinnedMesh::getMesh (this=0x600931220, frame=<optimized out>, detailLevel=<optimized out>, startFrameLoop=<optimized out>, endFrameLoop=-1) at /cygdrive/d/deve/stk-code/lib/irrlicht/source/Irrlicht/CSkinnedMesh.cpp:85
#6  0x00000001005600b8 in KartModel::loadModels (this=0x601ae6af0, kart_properties=...) at /cygdrive/d/deve/stk-code/src/karts/kart_model.cpp:525
#7  0x0000000100563c2d in KartProperties::load (this=0x601aaf7b0, filename=..., node=...) at /cygdrive/d/deve/stk-code/src/karts/kart_properties.cpp:266
#8  0x0000000100562ef7 in KartProperties::KartProperties (this=0x601aaf7b0, filename=...) at /cygdrive/d/deve/stk-code/src/karts/kart_properties.cpp:95
#9  0x0000000100569054 in KartPropertiesManager::loadKart (this=0x600e6a820, dir=...) at /cygdrive/d/deve/stk-code/src/karts/kart_properties_manager.cpp:247
#10 0x00000001005683a6 in KartPropertiesManager::loadAllKarts (this=0x600e6a820, loading_icon=true) at /cygdrive/d/deve/stk-code/src/karts/kart_properties_manager.cpp:165
#11 0x000000010057fec5 in main (argc=1, argv=0xffffcc10) at /cygdrive/d/deve/stk-code/src/main.cpp:1555
```

GLES renderer, not sure if it's related.

**Comment by deveee** [comment]
The problem disappeared after full rebuild, so maybe this is invalid. I'm closing for now.
