### ISSUE TITLE
Use FPV cam in cutscenes (sometimes) causes segfault

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#2876]
Seems to happen more with more complicated scenes (e.g. my new GPwin scene).

**Comment by deveee** [comment]
Could you provide a backtrace from debugger?

**Comment by qwertychouskie** [comment]
```
Thread 1 "supertuxkart" received signal SIGSEGV, Segmentation fault.
0x00007ffff569be48 in main_arena () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff569be48 in main_arena () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x0000555555ae0607 in CutsceneWorld::update (this=0x555558078820, 
    dt=0.0430000015)
    at /home/qwerty/stk-gpwin/stk-code/src/modes/cutscene_world.cpp:302
#2  0x0000555555af5e73 in World::updateWorld (this=0x555558078820, 
    dt=<optimized out>)
    at /home/qwerty/stk-gpwin/stk-code/src/modes/world.cpp:861
#3  0x0000555555addacc in MainLoop::run (this=0x5555572a3ee0)
    at /home/qwerty/stk-gpwin/stk-code/src/main_loop.cpp:248
#4  0x0000555555860832 in main (argc=<optimized out>, argv=<optimized out>)
    at /home/qwerty/stk-gpwin/stk-code/src/main.cpp:1780
```

**Comment by auriamg** [comment]
That seems to be the cutscene camera interfering with the FPS camera.

For now, just don't use the FPS cam in cutscenes... though fixes welcome.
