### ISSUE TITLE
STK crash when loading a track

### ISSUE THREAD

**Issue by Akasashasha** [supertuxkart/stk-code#3032]
Hello

this seems to happen randomly, please tell me if more details are needed:
- Windows 10
- Acer Aspire V15 V5-591G-54NE
- Inter HD Graphic + NVIDIA GForce GTX 950 M

thanks

**Comment by auriamg** [comment]
Is there any error message shown when this happens?

**Comment by Symbian9** [comment]
Oh, on Linux STK v0.9.3-rc1 failed each time when try start "3 Strike Battle" game with "*Temple*" arena. The only message described in terminal is `Segmantation Fault`.

**Comment by Akasashasha** [comment]
Hi

here is the error message I'm getting:

---------------------------
SuperTuxKart crashed :/
---------------------------
SuperTuxKart crashed!
Please hit Ctrl+C to copy to clipboard and signal the problem
to the developers on our forum: http://forum.freegamedev.net/viewforum.php?f=16

Call stack:

 memcpy
 asFreeMem
 asFreeMem
 asFreeMem
 asFreeMem
 asFreeMem
 asFreeMem
 asFreeMem
 asFreeMem
 asFreeMem
 BaseThreadInitThunk
 RtlGetAppContainerNamedObjectPath
 RtlGetAppContainerNamedObjectPath
---------------------------
OK   
---------------------------

**Comment by deveee** [comment]
@Symbian9 On linux you can run it under gdb to get a backtrace. Simplified backtrace is better than nothing... If you run our static package, then you can use:
```
export LD_LIBRARY_PATH=./lib-64
gdb ./bin-64/supertuxkart
```
and then
```r```
and after a crash
```bt```

**Comment by qwertychouskie** [comment]
@Akasashasha Can you post the contents of `%appdata%\supertuxkart\0.8.2\stdout.log`?

**Comment by Akasashasha** [comment]
Hi

I actually just installed the 0.9.3 Release Candidate and that solved the problem completely.
For Windows 10 users:

- uninstall STK
- go to C:/user/your_user_name/Appdata/ Roaming/ and delete the Supertuxkart folder (you will need to tick "hidden folders" to see it)
- restart your computer
- download the Release Candidate on the Supertuxkart website and install it
- restart your computer
- enjoy !

... and this new release is really great ! some improvements on graphic and design, less lag ... hope to see some new tracks soon.

Thanks to the whole STK team ! great job, our favorite Windows game so far (my son and myself :-) )

love


Christophe

**Comment by Symbian9** [comment]
@deveee, here is output of `gdb` for crash
* SuperTuxKart 0.9.3 RC1
* LinuxMint 18.2 (x86_64)
* ATI RS600 (OpenGL 2.1 Mesa 17.2.4)


```
mint@mint-SR58P ~/AppImages/supertuxkart $ export LD_LIBRARY_PATH=./lib-64
mint@mint-SR58P ~/AppImages/supertuxkart $ export LD_LIBRARY_PATH=./lib-64
mint@mint-SR58P ~/AppImages/supertuxkart $ gdb ./bin-64/supertuxkart
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./bin-64/supertuxkart...(no debugging symbols found)...done.
(gdb) r
Starting program: /home/mint/AppImages/supertuxkart/bin-64/supertuxkart 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[verbose  ] main: Error messages and other text output will be logged to /home/mint/.config/supertuxkart/0.8.2/stdout.log.
[info   ] [FileManager]: Data files will be fetched from: 'data/'
[info   ] [FileManager]: User directory is '/home/mint/.config/supertuxkart/0.8.2/'.
[info   ] [FileManager]: Addons files will be stored in '/home/mint/.local/share/supertuxkart/addons/'.
[info   ] [FileManager]: Screenshots will be stored in '/home/mint/.local/share/supertuxkart/screenshots/'.
[info   ] [FileManager]: User-defined grand prix will be stored in '/home/mint/.local/share/supertuxkart/grandprix/'.
[info   ] [FileManager]: Asset 0 will be loaded from 'data/challenges/'.
[info   ] [FileManager]: Asset 1 will be loaded from 'data/gfx/'.
[info   ] [FileManager]: Asset 2 will be loaded from 'data/grandprix/'.
[info   ] [FileManager]: Asset 3 will be loaded from 'data/gui/'.
[info   ] [FileManager]: Asset 4 will be loaded from 'data/library/'.
[info   ] [FileManager]: Asset 5 will be loaded from 'data/models/'.
[info   ] [FileManager]: Asset 6 will be loaded from 'data/music/'.
[info   ] [FileManager]: Asset 7 will be loaded from 'data/replay/'.
[info   ] [FileManager]: Asset 8 will be loaded from 'data/tracks/'.
[info   ] [FileManager]: Asset 9 will be loaded from 'data/sfx/'.
[info   ] [FileManager]: Asset 10 will be loaded from 'data/shaders/'.
[info   ] [FileManager]: Asset 11 will be loaded from 'data/skins/'.
[info   ] [FileManager]: Asset 12 will be loaded from 'data/textures/'.
[info   ] [FileManager]: Asset 13 will be loaded from 'data/ttf/'.
[info   ] [FileManager]: Asset 14 will be loaded from 'data/po/'.
[verbose  ] translation: Env var LANGUAGE = 'en_US'.
[verbose  ] translation: Language 'English (United States)'.
[warn   ] tinygettext: jbo.po: warning: ignoring, unknown language
[warn   ] tinygettext: no.po: warning: ignoring, unknown language
[warn   ] tinygettext: no_NO.po: warning: ignoring, unknown language
[warn   ] tinygettext: sc.po: warning: ignoring, unknown language
[warn   ] tinygettext: sco.po: warning: ignoring, unknown language
Adding language fallback en
[warn   ] tinygettext: jbo.po: warning: ignoring, unknown language
[warn   ] tinygettext: no.po: warning: ignoring, unknown language
[warn   ] tinygettext: no_NO.po: warning: ignoring, unknown language
[warn   ] tinygettext: sc.po: warning: ignoring, unknown language
[warn   ] tinygettext: sco.po: warning: ignoring, unknown language
Irrlicht Engine version 1.8.0
Linux 4.8.0-53-generic #56~16.04.1-Ubuntu SMP Tue May 16 01:18:56 UTC 2017 x86_64
[New Thread 0x7fffeb6bc700 (LWP 5907)]
[warn   ] [IrrDriver Temp Logger]: Level 2: No sRGB framebuffer available.

[info   ] IrrDriver: OpenGL version: 2.1
[info   ] IrrDriver: OpenGL vendor: X.Org R300 Project
[info   ] IrrDriver: OpenGL renderer: ATI RS600
[info   ] IrrDriver: OpenGL version string: 2.1 Mesa 17.2.4
[warn   ] irr_driver: Using the fixed pipeline (old GPU, or shaders disabled in options)
[New Thread 0x7fffe848d700 (LWP 5908)]
[New Thread 0x7fffea004700 (LWP 5909)]
[Thread 0x7fffea004700 (LWP 5909) exited]
[New Thread 0x7fffe5a9f700 (LWP 5910)]
[New Thread 0x7fffe5a9f700 (LWP 5911)]
[Thread 0x7fffe5a9f700 (LWP 5910) exited]
[New Thread 0x7fffe529e700 (LWP 5912)]
[New Thread 0x7fffe4847700 (LWP 5913)]
[info   ] GrandPrixManager: Loading Grand Prix files from data/grandprix/
[info   ] GrandPrixManager: Loading Grand Prix files from /home/mint/.local/share/supertuxkart/grandprix/
[warn   ] OpenGL: OpenGL version is too old!
[verbose  ] RaceManager: Nb of karts=2, ghost karts:0 ai:1 players:1


Thread 1 "supertuxkart" received signal SIGSEGV, Segmentation fault.
0x000000000096be28 in World::resetAllKarts() ()
(gdb) bt
#0  0x000000000096be28 in World::resetAllKarts() ()
#1  0x000000000096c01c in World::reset() ()
#2  0x0000000000978f41 in WorldWithRank::reset() ()
#3  0x000000000097dc26 in ThreeStrikesBattle::reset() ()
#4  0x000000000098bb2d in RaceManager::startNextRace() ()
#5  0x000000000098ce03 in RaceManager::startNew(bool) ()
#6  0x000000000098d71c in RaceManager::startSingleRace(std::string const&, int, bool) ()
#7  0x00000000007a6897 in TrackInfoScreen::onEnterPressedInternal() ()
#8  0x00000000007a7598 in TrackInfoScreen::eventCallback(GUIEngine::Widget*, std::string const&, int) ()
#9  0x000000000073e427 in GUIEngine::EventHandler::sendEventToUser(GUIEngine::Widget*, std::string&, int) ()
#10 0x000000000073e7f0 in GUIEngine::EventHandler::onWidgetActivated(GUIEngine::Widget*, int) ()
#11 0x000000000073eb81 in GUIEngine::EventHandler::onGUIEvent(irr::SEvent const&) ()
#12 0x000000000073ece6 in GUIEngine::EventHandler::OnEvent(irr::SEvent const&)
    ()
#13 0x0000000000cd24ea in irr::gui::CGUIButton::OnEvent(irr::SEvent const&) ()
#14 0x0000000000cd260b in irr::gui::CGUIButton::OnEvent(irr::SEvent const&) ()
#15 0x0000000000c333df in irr::gui::CGUIEnvironment::postEventFromUser(irr::SEvent const&) ()
---Type <return> to continue, or q <return> to quit---
#16 0x0000000000b63da9 in irr::CIrrDeviceStub::postEventFromUser(irr::SEvent const&) ()
#17 0x0000000000b5ee36 in irr::CIrrDeviceLinux::run() ()
#18 0x0000000000866658 in IrrDriver::update(float) ()
#19 0x0000000000969c7a in MainLoop::run() ()
#20 0x000000000071839a in main ()
(gdb) 
```

**Comment by Benau** [comment]
[patch.zip](https://github.com/supertuxkart/stk-code/files/1467704/patch.zip)
Try unpack the zip and replace those in tracks/temple folder?

**Comment by Symbian9** [comment]
> `patch_new.zip`

Well, now it work on Linux Mint 18.2.

P.S.: This "Temple" arena is too heavy and too slow on my laptop...

**Comment by Benau** [comment]
good
