### ISSUE TITLE
Crash in certain b3d tracks

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#3275]
Track: [faster-than-myself.zip](https://github.com/supertuxkart/stk-code/files/2043082/faster-than-myself.zip)

```
[info   ] HTTPRequest: Sending userid=15980&token=************************ to http://addons.supertuxkart.net/api/v2/user/poll/
[New Thread 0x7fffd7fff700 (LWP 20980)]
[Thread 0x7fffd7fff700 (LWP 20980) exited]
[warn   ] physics: Kart at (164.293503 5.148916 -15.000001) can not be dropped.
[warn   ] physics: Kart at (164.293503 5.148916 -15.000001) can not be dropped.
[warn   ] physics: Kart at (164.293503 5.148916 -15.000001) can not be dropped.
[warn   ] physics: Kart at (164.293503 5.148916 -15.000001) can not be dropped.
[warn   ] physics: Kart at (164.293503 5.148916 -15.000001) can not be dropped.
[warn   ] physics: Kart at (164.293503 5.148916 -15.000001) can not be dropped.
[warn   ] physics: Kart at (164.293503 4.991883 -15.000001) can not be dropped.
[warn   ] physics: Kart at (164.293503 5.148916 -15.000001) can not be dropped.
[warn   ] physics: Kart at (47.012249 5.143778 -90.854500) is too high above ground at (46.988445 0.077836 -90.808495)
[warn   ] physics: Kart at (51.925247 5.143778 -100.302505) is too high above ground at (51.898956 0.077835 -100.251717)

Thread 1 "supertuxkart" received signal SIGSEGV, Segmentation fault.
SP::Armature::getInterpolatedMatrices (this=this@entry=0x5555594544e0, 
    frame=frame@entry=-nan(0x400000))
    at /tmp/stk-code-master/src/graphics/sp/sp_animation.hpp:211
211	                (m_frame_pose_matrices[frame_1].second[i].m_loc, interpolation);
(gdb) bt
#0  SP::Armature::getInterpolatedMatrices (this=this@entry=0x5555594544e0, 
    frame=frame@entry=-nan(0x400000))
    at /tmp/stk-code-master/src/graphics/sp/sp_animation.hpp:211
#1  0x0000555555986ee4 in SP::Armature::getPose (dest=0x55555850fb90, 
    frame=-nan(0x400000), this=0x5555594544e0)
    at /tmp/stk-code-master/src/graphics/sp/sp_animation.hpp:145
#2  SP::SPMesh::getSkinningMatrices (this=this@entry=0x7fffc8003350, 
    frame=-nan(0x400000), dest=dest@entry=0x55555850fb90)
    at /tmp/stk-code-master/src/graphics/sp/sp_mesh.cpp:127
#3  0x0000555555993958 in SP::SPMeshNode::getMeshForCurrentFrame (
    this=0x55555b1c2670)
    at /tmp/stk-code-master/src/graphics/sp/sp_mesh_node.cpp:170
#4  0x0000555555d82f78 in irr::scene::CAnimatedMeshSceneNode::OnAnimate (
    this=0x55555b1c2670, timeMs=104347)
    at /tmp/stk-code-master/lib/irrlicht/source/Irrlicht/CAnimatedMeshSceneNode.cpp:244
#5  0x0000555555d83055 in irr::scene::ISceneNode::OnAnimate (timeMs=104347, 
    this=<optimized out>)
    at /tmp/stk-code-master/lib/irrlicht/include/ISceneNode.h:132
#6  irr::scene::CAnimatedMeshSceneNode::OnAnimate (this=<optimized out>, 
    timeMs=104347)
    at /tmp/stk-code-master/lib/irrlicht/source/Irrlicht/CAnimatedMeshSceneNode.cpp:251
---Type <return> to continue, or q <return> to quit---
#7  0x0000555555927bb0 in LODNode::OnAnimate (this=0x55555a9b2aa0, 
    timeMs=104347) at /tmp/stk-code-master/src/graphics/lod_node.cpp:116
#8  0x0000555555953d4c in irr::scene::ISceneNode::OnAnimate (timeMs=104347, 
    this=0x55555652b0a8)
    at /tmp/stk-code-master/lib/irrlicht/include/ISceneNode.h:132
#9  ShaderBasedRenderer::render (this=0x55555674f180, dt=0.0166666675)
    at /tmp/stk-code-master/src/graphics/shader_based_renderer.cpp:724
#10 0x000055555590f55d in IrrDriver::update (this=0x555556523da0, 
    dt=dt@entry=0.0166666675)
    at /tmp/stk-code-master/src/graphics/irr_driver.cpp:1884
#11 0x0000555555ac9015 in MainLoop::run (this=0x555558ae4bd0)
    at /tmp/stk-code-master/src/main_loop.cpp:372
#12 0x000055555584e84d in main (argc=<optimized out>, argv=<optimized out>)
    at /tmp/stk-code-master/src/main.cpp:1957
```
With only official karts:
```
Thread 1 "supertuxkart" received signal SIGSEGV, Segmentation fault.
0x0000555555c93506 in DriveGraph::getNode (this=0x55555b1c7e30, j=4294967295)
    at /tmp/stk-code-master/src/tracks/drive_graph.cpp:723
723	    DriveNode* n = dynamic_cast<DriveNode*>(m_all_nodes[j]);
(gdb) bt
#0  0x0000555555c93506 in DriveGraph::getNode (this=0x55555b1c7e30, 
    j=4294967295) at /tmp/stk-code-master/src/tracks/drive_graph.cpp:723
#1  0x0000555555cbbe8d in TrackSector::update (this=0x55555b7f8e80, xyz=..., 
    ignore_vertical=<optimized out>)
    at /tmp/stk-code-master/src/tracks/track_sector.cpp:82
#2  0x0000555555ad0425 in LinearWorld::update (this=0x55555b5c6ef0, ticks=1)
    at /tmp/stk-code-master/src/modes/linear_world.cpp:182
#3  0x0000555555ae1c03 in World::updateWorld (this=0x55555b5c6ef0, ticks=1)
    at /tmp/stk-code-master/src/modes/world.cpp:877
#4  0x0000555555ac8a23 in MainLoop::updateRace (
    this=this@entry=0x555558f06200, ticks=ticks@entry=1)
    at /tmp/stk-code-master/src/main_loop.cpp:209
#5  0x0000555555ac8c72 in MainLoop::run (this=0x555558f06200)
    at /tmp/stk-code-master/src/main_loop.cpp:397
#6  0x000055555584e90d in main (argc=<optimized out>, argv=<optimized out>)
    at /tmp/stk-code-master/src/main.cpp:1957
```

**Comment by Benau** [comment]
don't edit track.xml to port addon. re-export properly
