### ISSUE TITLE
Crash when finish battle mode

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#3316]
```
#0  0x00005555560c5d8e in GUIEngine::Widget::isVisible (this=0x0) at /home/Dokumenty/programowanie/supertuxkart/supertuxkart-git/src/guiengine/widget.cpp:310
#1  0x000055555609fbe7 in GUIEngine::EventHandler::findIDClosestWidget (this=0x55555966a9a0, nav=GUIEngine::NAV_UP, playerID=0, w=0x555567ad2580, ignore_disabled=true, recursion_counter=3)
    at /home/Dokumenty/programowanie/supertuxkart/supertuxkart-git/src/guiengine/event_handler.cpp:622
#2  0x000055555609fc75 in GUIEngine::EventHandler::findIDClosestWidget (this=0x55555966a9a0, nav=GUIEngine::NAV_UP, playerID=0, w=0x55556e6fe930, ignore_disabled=false, recursion_counter=3)
    at /home/Dokumenty/programowanie/supertuxkart/supertuxkart-git/src/guiengine/event_handler.cpp:635
#3  0x000055555609fc3d in GUIEngine::EventHandler::findIDClosestWidget (this=0x55555966a9a0, nav=GUIEngine::NAV_UP, playerID=0, w=0x55556e5b84f0, ignore_disabled=false, recursion_counter=3)
    at /home/Dokumenty/programowanie/supertuxkart/supertuxkart-git/src/guiengine/event_handler.cpp:628
#4  0x000055555609fc3d in GUIEngine::EventHandler::findIDClosestWidget (this=0x55555966a9a0, nav=GUIEngine::NAV_UP, playerID=0, w=0x555567ad2580, ignore_disabled=false, recursion_counter=2)
    at /home/Dokumenty/programowanie/supertuxkart/supertuxkart-git/src/guiengine/event_handler.cpp:628
#5  0x000055555609f6f8 in GUIEngine::EventHandler::navigate (this=0x55555966a9a0, nav=GUIEngine::NAV_UP, playerID=0)
    at /home/Dokumenty/programowanie/supertuxkart/supertuxkart-git/src/guiengine/event_handler.cpp:464
#6  0x000055555609f696 in GUIEngine::EventHandler::sendNavigationEvent (this=0x55555966a9a0, nav=GUIEngine::NAV_UP, playerID=0)
    at /home/Dokumenty/programowanie/supertuxkart/supertuxkart-git/src/guiengine/event_handler.cpp:450
#7  0x000055555609f340 in GUIEngine::EventHandler::processGUIAction (this=0x55555966a9a0, action=PA_MENU_UP, deviceID=0, value=0, type=Input::IT_KEYBOARD, playerID=0)
    at /home/Dokumenty/programowanie/supertuxkart/supertuxkart-git/src/guiengine/event_handler.cpp:330
#8  0x00005555561171df in InputManager::dispatchInput (this=0x555559789550, type=Input::IT_KEYBOARD, deviceID=0, button=85, axisDirection=Input::AD_POSITIVE, value=0, shift_mask=false)
    at /home/Dokumenty/programowanie/supertuxkart/supertuxkart-git/src/input/input_manager.cpp:882
#9  0x00005555561178a3 in InputManager::input (this=0x555559789550, event=...) at /home/Dokumenty/programowanie/supertuxkart/supertuxkart-git/src/input/input_manager.cpp:1071
#10 0x000055555609f066 in GUIEngine::EventHandler::OnEvent (this=0x55555966a9a0, event=...) at /home/Dokumenty/programowanie/supertuxkart/supertuxkart-git/src/guiengine/event_handler.cpp:238
#11 0x00005555565369c2 in irr::CIrrDeviceStub::postEventFromUser (this=0x555557101040, event=...)
    at /home/Dokumenty/programowanie/supertuxkart/supertuxkart-git/lib/irrlicht/source/Irrlicht/CIrrDeviceStub.cpp:224
#12 0x000055555652f1cb in irr::CIrrDeviceLinux::run (this=0x555557101040) at /home/Dokumenty/programowanie/supertuxkart/supertuxkart-git/lib/irrlicht/source/Irrlicht/CIrrDeviceLinux.cpp:1877
#13 0x0000555555f97ed8 in IrrDriver::update (this=0x555557120750, dt=0.0166666675) at /home/Dokumenty/programowanie/supertuxkart/supertuxkart-git/src/graphics/irr_driver.cpp:1853
---Type <return> to continue, or q <return> to quit---
#14 0x0000555556200a68 in MainLoop::run (this=0x55555d915ef0) at /home/Dokumenty/programowanie/supertuxkart/supertuxkart-git/src/main_loop.cpp:372
#15 0x00005555561f7e67 in main (argc=1, argv=0x7fffffffe518) at /home/Dokumenty/programowanie/supertuxkart/supertuxkart-git/src/main.cpp:2023
(gdb) 
```
Up key was pressed before widget was displayed?

**Comment by Alayan-stk-2** [comment]
I will investigate, as it's related to the new navigation method.
