### ISSUE TITLE
Crash in friend search box with special characters

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3457]
The character * triggers a crash in the user search box in the friends tab of the online profile ; this may be possible with other characters.

backtrace : 
```
#0  OnlineUserSearch::parseResult (this=this@entry=0xc1ac4a0, 
    input=0x7fffdd0078e0)
    at /*/src/states_screens/online_user_search.cpp:142
#1  0x0000000000840c9f in OnlineUserSearch::onUpdate (this=0xc1ac4a0, 
    dt=<optimized out>)
    at /*/src/states_screens/online_user_search.cpp:251
#2  0x0000000000756b8c in GUIEngine::render (
    elapsed_time=elapsed_time@entry=0.0166666675)
    at /*/src/guiengine/engine.cpp:1178
#3  0x0000000000a28ffe in IrrDriver::update (this=0x13a9fa0, 
    dt=dt@entry=0.0166666675)
    at /*/src/graphics/irr_driver.cpp:1903
#4  0x000000000075c2fc in MainLoop::run (this=0x7e4e110)
    at /*/src/main_loop.cpp:380
#5  0x000000000063a85a in main (argc=<optimized out>, argv=<optimized out>)
    at /*/src/main.cpp:2175
```

**Comment by Alayan-stk-2** [comment]
After some more tests, this seems specifically related to the * character. Some characters like $ return generic results, some other like ! produce an empty result list, but so far, only * has managed to trigger a crash - and it so with 100% reliability.
