### ISSUE TITLE
Network splitscreen crash

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#3606]
I used "enable splitscreen or handicap". Then I created a server and added one player. Then I closed a server and I pressed "local networking" button once again. In this case it tries to use kart selection screen, which is null btw.

```
(gdb) bt
#0  0x00005555561937d4 in std::vector<GUIEngine::PlayerKartWidget*, std::allocator<GUIEngine::PlayerKartWidget*> >::size (this=0x70)
    at /usr/include/c++/7/bits/stl_vector.h:671
#1  0x0000555556193746 in PtrVector<GUIEngine::PlayerKartWidget, (VECTOR_TYPE)0>::size (this=0x70)
    at /home/Dokumenty/programowanie/supertuxkart/supertuxkart-git/src/utils/ptr_vector.hpp:103
#2  0x0000555556487da1 in KartSelectionScreen::joinPlayer (this=0x0, device=
    0x55555a28b350, p=0x0)
    at /home/Dokumenty/programowanie/supertuxkart/supertuxkart-git/src/states_screens/kart_selection.cpp:445
#3  0x00005555561b600e in InputManager::dispatchInput (this=0x5555577354a0, 
    type=Input::IT_KEYBOARD, deviceID=0, button=162, 
    axisDirection=Input::AD_POSITIVE, value=32768, shift_mask=false)
    at /home/Dokumenty/programowanie/supertuxkart/supertuxkart-git/src/input/input_manager.cpp:784
#4  0x00005555561b6a53 in InputManager::input (this=0x5555577354a0, event=...)
    at /home/Dokumenty/programowanie/supertuxkart/supertuxkart-git/src/input/input_manager.cpp:1046
#5  0x0000555556138b3f in GUIEngine::EventHandler::OnEvent (
    this=0x55555773f7f0, event=...)
    at /home/Dokumenty/programowanie/supertuxkart/supertuxkart-git/src/guiengine/event_handler.cpp:240
---Type <return> to continue, or q <return> to quit---
#6  0x0000555556650a92 in irr::CIrrDeviceStub::postEventFromUser (
    this=0x555557265bb0, event=...)
    at /home/Dokumenty/programowanie/supertuxkart/supertuxkart-git/lib/irrlicht/source/Irrlicht/CIrrDeviceStub.cpp:224
#7  0x000055555664922b in irr::CIrrDeviceLinux::run (this=0x555557265bb0)
    at /home/Dokumenty/programowanie/supertuxkart/supertuxkart-git/lib/irrlicht/source/Irrlicht/CIrrDeviceLinux.cpp:1882
#8  0x00005555562bc8d9 in MainLoop::run (this=0x55555b6e4bf0)
    at /home/Dokumenty/programowanie/supertuxkart/supertuxkart-git/src/main_loop.cpp:509
#9  0x00005555562b209a in main (argc=1, argv=0x7fffffffe4e8)
    at /home/Dokumenty/programowanie/supertuxkart/supertuxkart-git/src/main.cpp:2231
```

**Comment by deveee** [comment]
Ok fixed in https://github.com/supertuxkart/stk-code/commit/8771f0b9d7badaa024209025ebdb253247b3f971
