### ISSUE TITLE
Segmentation fault (core dumped) 1.0

### ISSUE THREAD

**Issue by Souravgoswami** [supertuxkart/stk-code#4151]
Hi, I am using ArchLinux x86_64. I noticed after a system upgrade, supertuxkart 1.0 keeps crashing.

Before I am writing, I have downloaded the a moment ago, extracted it and ran `run_game.sh` script. After that it loads the game frame, and then it crashes with the errors:

```
⮚ ./run_game.sh 
Running 64-bit version...
[verbose  ] main: Error messages and other text output will be logged to /home/sourav/.config/supertuxkart/config-0.10/stdout.log.
[error  ] User Config: Unknown value for hidpi_enabled; expected true or false
[error  ] User Config: Unknown value for vsync; expected true or false
[info   ] [FileManager]: Data files will be fetched from: '/home/sourav/Downloads/supertuxkart-1.0-linux/data/'
[info   ] [FileManager]: User directory is '/home/sourav/.config/supertuxkart/config-0.10/'.
[info   ] [FileManager]: Addons files will be stored in '/home/sourav/.local/share/supertuxkart/addons/'.
[info   ] [FileManager]: Screenshots will be stored in '/home/sourav/.local/share/supertuxkart/screenshots/'.
[info   ] [FileManager]: User-defined grand prix will be stored in '/home/sourav/.local/share/supertuxkart/grandprix/'.
[info   ] [FileManager]: Asset 0 will be loaded from '/home/sourav/Downloads/supertuxkart-1.0-linux/data/challenges/'.
[info   ] [FileManager]: Asset 1 will be loaded from '/home/sourav/Downloads/supertuxkart-1.0-linux/data/gfx/'.
[info   ] [FileManager]: Asset 2 will be loaded from '/home/sourav/Downloads/supertuxkart-1.0-linux/data/grandprix/'.
[info   ] [FileManager]: Asset 3 will be loaded from '/home/sourav/Downloads/supertuxkart-1.0-linux/data/gui/icons/'.
[info   ] [FileManager]: Asset 4 will be loaded from '/home/sourav/Downloads/supertuxkart-1.0-linux/data/gui/screens/'.
[info   ] [FileManager]: Asset 5 will be loaded from '/home/sourav/Downloads/supertuxkart-1.0-linux/data/gui/dialogs/'.
[info   ] [FileManager]: Asset 6 will be loaded from '/home/sourav/Downloads/supertuxkart-1.0-linux/data/library/'.
[info   ] [FileManager]: Asset 7 will be loaded from '/home/sourav/Downloads/supertuxkart-1.0-linux/data/models/'.
[info   ] [FileManager]: Asset 8 will be loaded from '/home/sourav/Downloads/supertuxkart-1.0-linux/data/music/'.
[info   ] [FileManager]: Asset 9 will be loaded from '/home/sourav/Downloads/supertuxkart-1.0-linux/data/replay/'.
[info   ] [FileManager]: Asset 10 will be loaded from '/home/sourav/Downloads/supertuxkart-1.0-linux/data/tracks/'.
[info   ] [FileManager]: Asset 11 will be loaded from '/home/sourav/Downloads/supertuxkart-1.0-linux/data/sfx/'.
[info   ] [FileManager]: Asset 12 will be loaded from '/home/sourav/Downloads/supertuxkart-1.0-linux/data/shaders/'.
[info   ] [FileManager]: Asset 13 will be loaded from '/home/sourav/Downloads/supertuxkart-1.0-linux/data/skins/'.
[info   ] [FileManager]: Asset 14 will be loaded from '/home/sourav/Downloads/supertuxkart-1.0-linux/data/textures/'.
[info   ] [FileManager]: Asset 15 will be loaded from '/home/sourav/Downloads/supertuxkart-1.0-linux/data/ttf/'.
[info   ] [FileManager]: Asset 16 will be loaded from '/home/sourav/Downloads/supertuxkart-1.0-linux/data/po/'.
[verbose  ] translation: Env var LANGUAGE = 'en_GB.UTF-8'.
[verbose  ] translation: Language 'English (Great Britain)'.
[info   ] tinygettext: Adding language fallback en

..:: Antarctica Rendering Engine 2.0 ::..
Linux 5.3.11-arch1-1 #1 SMP PREEMPT Tue, 12 Nov 2019 22:19:48 +0000 x86_64
[info   ] IrrDriver: OpenGL version: 4.5
[info   ] IrrDriver: OpenGL vendor: Intel Open Source Technology Center
[info   ] IrrDriver: OpenGL renderer: Mesa DRI Intel(R) Haswell 
[info   ] IrrDriver: OpenGL version string: 4.5 (Core Profile) Mesa 19.2.4
[info   ] GLDriver: ARB Buffer Storage Present
[info   ] GLDriver: ARB Compute Shader Present
[info   ] GLDriver: ARB Arrays of Arrays Present
[info   ] GLDriver: ARB Texture Storage Present
[info   ] GLDriver: ARB Texture View Present
[info   ] GLDriver: ARB Image Load Store Present
[info   ] GLDriver: ARB Shader Atomic Counters Present
[info   ] GLDriver: ARB Shader Storage Buffer Object Present
[info   ] GLDriver: EXT Texture Compression S3TC Present
[info   ] GLDriver: ARB Uniform Buffer Object Present
[info   ] GLDriver: ARB Explicit Attrib Location Present
[info   ] GLDriver: EXT Texture Filter Anisotropic Present
[info   ] GLDriver: Geometry Shaders Present
[info   ] GLDriver: ARB Texture Buffer Object Present
[info   ] GLDriver: ARB Texture Swizzle Present
[info   ] GLDriver: ARB Pixel Buffer Object Present
[info   ] GLDriver: ARB Sampler Objects Present
[info   ] GLDriver: ARB Vertex Type 2_10_10_10_rev Present
[info   ] GLDriver: ARB Instanced Arrays Present
[info   ] SharedGPUObjects: Hardware Skinning enabled, method: TBO, max bones: 1024
[info   ] ShaderFilesManager: Compiling shader: /home/sourav/Downloads/supertuxkart-1.0-linux/data/shaders/sp_pass.vert
[info   ] ShaderFilesManager: Compiling shader: /home/sourav/Downloads/supertuxkart-1.0-linux/data/shaders/sp_solid.frag
[info   ] ShaderFilesManager: Compiling shader: /home/sourav/Downloads/supertuxkart-1.0-linux/data/shaders/sp_shadow.vert
[info   ] ShaderFilesManager: Compiling shader: /home/sourav/Downloads/supertuxkart-1.0-linux/data/shaders/white.frag
[info   ] ShaderFilesManager: Compiling shader: /home/sourav/Downloads/supertuxkart-1.0-linux/data/shaders/sp_skinning.vert
[info   ] ShaderFilesManager: Compiling shader: /home/sourav/Downloads/supertuxkart-1.0-linux/data/shaders/sp_skinning_shadow.vert
[info   ] ShaderFilesManager: Compiling shader: /home/sourav/Downloads/supertuxkart-1.0-linux/data/shaders/sp_normal_map.frag
[info   ] ShaderFilesManager: Compiling shader: /home/sourav/Downloads/supertuxkart-1.0-linux/data/shaders/sp_alpha_test.frag
[info   ] ShaderFilesManager: Compiling shader: /home/sourav/Downloads/supertuxkart-1.0-linux/data/shaders/sp_shadow_alpha_test.frag
[info   ] ShaderFilesManager: Compiling shader: /home/sourav/Downloads/supertuxkart-1.0-linux/data/shaders/sp_decal.frag
[info   ] ShaderFilesManager: Compiling shader: /home/sourav/Downloads/supertuxkart-1.0-linux/data/shaders/sp_grass_pass.vert
[info   ] ShaderFilesManager: Compiling shader: /home/sourav/Downloads/supertuxkart-1.0-linux/data/shaders/sp_grass.frag
[info   ] ShaderFilesManager: Compiling shader: /home/sourav/Downloads/supertuxkart-1.0-linux/data/shaders/sp_grass_shadow.vert
[info   ] ShaderFilesManager: Compiling shader: /home/sourav/Downloads/supertuxkart-1.0-linux/data/shaders/sp_unlit.frag
[info   ] ShaderFilesManager: Compiling shader: /home/sourav/Downloads/supertuxkart-1.0-linux/data/shaders/sp_transparent.frag
[info   ] ShaderFilesManager: Compiling shader: /home/sourav/Downloads/supertuxkart-1.0-linux/data/shaders/sp_ghost.frag
[info   ] ShaderFilesManager: Compiling shader: /home/sourav/Downloads/supertuxkart-1.0-linux/data/shaders/sp_dynamic_night_bloom.frag
[info   ] ShaderFilesManager: Compiling shader: /home/sourav/Downloads/supertuxkart-1.0-linux/data/shaders/sp_tilling_mitigation.frag
[info   ] ShaderFilesManager: Compiling shader: /home/sourav/Downloads/supertuxkart-1.0-linux/data/shaders/sp_vertical_mapping.frag
[info   ] ShaderFilesManager: Compiling shader: /home/sourav/Downloads/supertuxkart-1.0-linux/data/shaders/sp_road_blending.frag
[info   ] ShaderFilesManager: Compiling shader: /home/sourav/Downloads/supertuxkart-1.0-linux/data/shaders/sp_displace.frag
[info   ] ShaderFilesManager: Compiling shader: /home/sourav/Downloads/supertuxkart-1.0-linux/data/shaders/colorize.frag
[info   ] ShaderFilesManager: Compiling shader: /home/sourav/Downloads/supertuxkart-1.0-linux/data/shaders/sp_normal_visualizer.vert
[info   ] ShaderFilesManager: Compiling shader: /home/sourav/Downloads/supertuxkart-1.0-linux/data/shaders/sp_normal_visualizer.geom
[info   ] ShaderFilesManager: Compiling shader: /home/sourav/Downloads/supertuxkart-1.0-linux/data/shaders/sp_normal_visualizer.frag
[info   ] ShaderFilesManager: Compiling shader: /home/sourav/Downloads/supertuxkart-1.0-linux/data/shaders/screenquad.vert
[info   ] ShaderFilesManager: Compiling shader: /home/sourav/Downloads/supertuxkart-1.0-linux/data/shaders/motion_blur.frag
[info   ] ShaderFilesManager: Compiling shader: /home/sourav/Downloads/supertuxkart-1.0-linux/data/shaders/lightning.frag
[info   ] ShaderFilesManager: Compiling shader: /home/sourav/Downloads/supertuxkart-1.0-linux/data/shaders/primitive2dlist.vert
[info   ] ShaderFilesManager: Compiling shader: /home/sourav/Downloads/supertuxkart-1.0-linux/data/shaders/transparent.frag
[info   ] ShaderFilesManager: Compiling shader: /home/sourav/Downloads/supertuxkart-1.0-linux/data/shaders/texturedquad.vert
[info   ] ShaderFilesManager: Compiling shader: /home/sourav/Downloads/supertuxkart-1.0-linux/data/shaders/uniformcolortexturedquad.frag
[info   ] ShaderFilesManager: Compiling shader: /home/sourav/Downloads/supertuxkart-1.0-linux/data/shaders/texturedquad.frag
[info   ] ShaderFilesManager: Compiling shader: /home/sourav/Downloads/supertuxkart-1.0-linux/data/shaders/coloredquad.vert
[info   ] ShaderFilesManager: Compiling shader: /home/sourav/Downloads/supertuxkart-1.0-linux/data/shaders/coloredquad.frag
[info   ] ShaderFilesManager: Compiling shader: /home/sourav/Downloads/supertuxkart-1.0-linux/data/shaders/colortexturedquad.vert
[info   ] ShaderFilesManager: Compiling shader: /home/sourav/Downloads/supertuxkart-1.0-linux/data/shaders/colortexturedquad.frag
[info   ] irr_driver: GLSL supported.
./run_game.sh: line 20:  2468 Segmentation fault      (core dumped) "$DIRNAME/bin-64/supertuxkart" $@
```

OpenGL Details (reported by glxinfo):
```
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Haswell 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.2.4
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 19.2.4
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 19.2.4
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
```

Video Driver Details (running xorg):
```
xf86-video-intel 1:2.99.917+895+gcb6bff95-1
xf86-video-vesa 2.4.0-2
```

It happening since a couple of months probably...

**Comment by Benau** [comment]
```
coredumpctl gdb supertuxkart
(gdb) bt
```
And then can you paste the terminal output here?

Also have you ever tried git stk?

**Comment by Souravgoswami** [comment]
When I run the above commands:

```
⮚ coredumpctl gdb supertuxkart
Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal', 'wheel' can see all messages.
      Pass -q to turn off this notice.
           PID: 2468 (supertuxkart)
           UID: 1000 (sourav)
           GID: 1000 (sourav)
        Signal: 11 (SEGV)
     Timestamp: Fri 2019-11-29 23:42:42 IST (51min ago)
  Command Line: /home/sourav/Downloads/supertuxkart-1.0-linux/bin-64/supertuxkart
    Executable: /home/sourav/Downloads/supertuxkart-1.0-linux/bin-64/supertuxkart
 Control Group: /user.slice/user-1000.slice/user@1000.service/gnome-terminal-server.service
          Unit: user@1000.service
     User Unit: gnome-terminal-server.service
         Slice: user-1000.slice
     Owner UID: 1000 (sourav)
       Boot ID: 92e317ac0a9e47d9b08af72f680af0a7
    Machine ID: 6afdd4c904f34e57b7968d2f88472941
      Hostname: archlinux-pc
       Storage: /var/lib/systemd/coredump/core.supertuxkart.1000.92e317ac0a9e47d9b08af72f680af0a7.2468.1575051162000000000000.lz4
       Message: Process 2468 (supertuxkart) of user 1000 dumped core.
                
                Stack trace of thread 2468:
                #0  0x00000000009bdf34 n/a (/home/sourav/Downloads/supertuxkart-1.0-linux/bin-64/supertuxkart)

GNU gdb (GDB) 8.3.1
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/sourav/Downloads/supertuxkart-1.0-linux/bin-64/supertuxkart...
(No debugging symbols found in /home/sourav/Downloads/supertuxkart-1.0-linux/bin-64/supertuxkart)
[New LWP 2468]
[New LWP 2474]
[New LWP 2472]
[New LWP 2473]
[New LWP 2470]
[New LWP 2471]
[New LWP 2469]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `/home/sourav/Downloads/supertuxkart-1.0-linux/bin-64/supertuxkart'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000009bdf34 in GUIEngine::Skin::drawBgImage() ()
--Type <RET> for more, q to quit, c to continue without paging--
[Current thread is 1 (Thread 0x7f68ae5fa740 (LWP 2468))]
/usr/lib/../share/gcc-9.2.0/python/libstdcxx/v6/xmethods.py:731: SyntaxWarning: list indices must be integers or slices, not str; perhaps you missed a comma?
  refcounts = ['_M_refcount']['_M_pi']
(gdb) bt
#0  0x00000000009bdf34 in GUIEngine::Skin::drawBgImage() ()
#1  0x00000000009b52b0 in GUIEngine::renderLoading(bool) ()
#2  0x00000000009b5d78 in GUIEngine::init(irr::IrrlichtDevice*, irr::video::IVideoDriver*, GUIEngine::AbstractStateManager*) ()
#3  0x0000000000783d43 in initRest() ()
#4  0x00000000006c7626 in main ()
```

I haven't tried the git stk. I have download it from supertuxkart.net...

**Comment by Benau** [comment]
can you try remove the config.xml in your .config/supertuxkart/config-0.10 and retry?

**Comment by Benau** [comment]
hmm you did try git stk version:
```
[error  ] User Config: Unknown value for hidpi_enabled; expected true or false
[error  ] User Config: Unknown value for vsync; expected true or false
```
So remove your config.xml should work (or if you git pull to latest it will work too, so imcompatible config is renamed)
