### ISSUE TITLE
Supertuxkart crashing on startup

### ISSUE THREAD

**Issue by TheEt1234** [supertuxkart/stk-code#4594]
## Description
Supertuxkart is crashing on startup (Segmentation fault)

## Configuration

STK release version: whatever the latest is

I downloaded STK from official arch gnu/linux repos
System:  Arch GNU/Linux

Graphics card: AMD ATI Radeon R7 M265/M365X/M465 & Intel Haswell-ULT

CPU: Intel i3-4010U (4) @ 1.700GHz

## Additional information
stdout.log:
```
[info   ] [FileManager]: Data files will be fetched from: '/usr/share/supertuxkart/data/'
[info   ] [FileManager]: User directory is '/home/et/.config/supertuxkart/config-0.10/'.
[info   ] [FileManager]: Addons files will be stored in '/home/et/.local/share/supertuxkart/addons/'.
[info   ] [FileManager]: Screenshots will be stored in '/home/et/.local/share/supertuxkart/screenshots/'.
[info   ] [FileManager]: User-defined grand prix will be stored in '/home/et/.local/share/supertuxkart/grandprix/'.
[info   ] [FileManager]: Asset 0 will be loaded from '/usr/share/supertuxkart/data/challenges/'.
[info   ] [FileManager]: Asset 1 will be loaded from '/usr/share/supertuxkart/data/gfx/'.
[info   ] [FileManager]: Asset 2 will be loaded from '/usr/share/supertuxkart/data/grandprix/'.
[info   ] [FileManager]: Asset 3 will be loaded from '/usr/share/supertuxkart/data/gui/icons/'.
[info   ] [FileManager]: Asset 4 will be loaded from '/usr/share/supertuxkart/data/gui/screens/'.
[info   ] [FileManager]: Asset 5 will be loaded from '/usr/share/supertuxkart/data/gui/dialogs/'.
[info   ] [FileManager]: Asset 6 will be loaded from '/usr/share/supertuxkart/data/replay/'.
[info   ] [FileManager]: Asset 7 will be loaded from '/usr/share/supertuxkart/data/shaders/'.
[info   ] [FileManager]: Asset 8 will be loaded from '/usr/share/supertuxkart/data/skins/'.
[info   ] [FileManager]: Asset 9 will be loaded from '/usr/share/supertuxkart/data/ttf/'.
[info   ] [FileManager]: Asset 10 will be loaded from '/usr/share/supertuxkart/data/po/'.
[info   ] [FileManager]: Asset 11 will be loaded from '/usr/share/supertuxkart/data/library/'.
[info   ] [FileManager]: Asset 12 will be loaded from '/usr/share/supertuxkart/data/models/'.
[info   ] [FileManager]: Asset 13 will be loaded from '/usr/share/supertuxkart/data/music/'.
[info   ] [FileManager]: Asset 14 will be loaded from '/usr/share/supertuxkart/data/sfx/'.
[info   ] [FileManager]: Asset 15 will be loaded from '/usr/share/supertuxkart/data/textures/'.
[info   ] [FileManager]: Asset 16 will be loaded from '/usr/share/supertuxkart/data/tracks/'.
[verbose  ] translation: Env var LANGUAGE = 'en_US.UTF-8'.
[verbose  ] translation: Language 'English (United States)'.
[info   ] tinygettext: Adding language fallback en

[info   ] IrrDriver: OpenGL version: 3.2
[info   ] IrrDriver: OpenGL vendor: Intel Open Source Technology Center
[info   ] IrrDriver: OpenGL renderer: Mesa DRI Intel(R) HD Graphics 4400 (HSW GT2)
[info   ] IrrDriver: OpenGL version string: 3.2 (Compatibility Profile) Mesa 21.2.1
[info   ] GLDriver: ARB Buffer Storage Present
[info   ] GLDriver: ARB Compute Shader Present
[info   ] GLDriver: ARB Arrays of Arrays Present
[info   ] GLDriver: ARB Texture Storage Present
[info   ] GLDriver: ARB Texture View Present
[info   ] GLDriver: ARB Image Load Store Present
[info   ] GLDriver: ARB Shader Atomic Counters Present
[info   ] GLDriver: ARB Shader Storage Buffer Object Present
[info   ] GLDriver: EXT Texture Compression S3TC Present
[info   ] GLDriver: ARB Uniform Buffer Object Present
[info   ] GLDriver: ARB Explicit Attrib Location Present
[info   ] GLDriver: EXT Texture Filter Anisotropic Present
[info   ] GLDriver: Geometry Shaders Present
[info   ] GLDriver: ARB Texture Buffer Object Present
[info   ] GLDriver: ARB Texture Swizzle Present
[info   ] GLDriver: ARB Pixel Buffer Object Present
[info   ] GLDriver: ARB Sampler Objects Present
[info   ] GLDriver: ARB Vertex Type 2_10_10_10_rev Present
[info   ] GLDriver: ARB Instanced Arrays Present
[warn   ] SharedGPUObjects: Too many bones for skinning, max: 0
[info   ] SharedGPUObjects: Hardware Skinning enabled, method: TBO, max bones: 0
```

Error message(s):
```
[warn   ] SharedGPUObjects: Too many bones for skinning, max: 0

Segmentation fault (core dumped)
```

## What i tried

I tried reinstalling STK
and deleting the configs
none of those work

**Comment by TheEt1234** [comment]
gdb bt output:

```
#0  0x00005593465bd583 in SP::resizeSkinning(unsigned int) ()
[Current thread is 1 (Thread 0x7f12c44e9780 (LWP 46164))]
(gdb) bt
#0  0x00005593465bd583 in SP::resizeSkinning(unsigned int) ()
#1  0x00005593465bd847 in SP::initSkinning() ()
#2  0x00005593465bf49d in SP::init() ()
#3  0x000055934659b50f in ShaderBasedRenderer::ShaderBasedRenderer() ()
#4  0x000055934654a3d7 in IrrDriver::initDevice() ()
#5  0x0000559346777236 in initRest() ()
#6  0x0000559346450bde in main ()

```

**Comment by Benau** [comment]
because you are using opengl 3.2, make sure you have no custom environment variable set to restrict max opengl version

hd4400 should support at least opengl 4.x

**Comment by TheEt1234** [comment]
> because you are using opengl 3.2, make sure you have no custom environment variable set to restrict max opengl version
> 
> hd4400 should support at least opengl 4.x

Oh that was the problem, thanks so much
