### ISSUE TITLE
SuperTuxKart crashes when entering any online map

### ISSUE THREAD

**Issue by VxlerieUwU** [supertuxkart/stk-code#5057]
## Steps to reproduce
Launch STK, join any online server, start the game, crash after entering the map (loading.... screen, kart is in the air)

## Configuration

STK release version: git 23267+18587-1

STK Source (PPA, distribution package, official binary, etc.): repo.archlinuxcn.org

System: ThinkPad P51, archlinux

Graphics card: NVIDIA Quadro M2200 Mobile

CPU: Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz

## Additional information

stdout.log:
Possibly related to #5056   

```
[info   ] [FileManager]: Data files will be fetched from: '/usr/share/supertuxkart/data/'
[info   ] [FileManager]: User directory is '/home/user/.config/supertuxkart/config-0.10/'.
[info   ] [FileManager]: Addons files will be stored in '/home/user/.local/share/supertuxkart/addons/'.
[info   ] [FileManager]: Screenshots will be stored in '/home/user/.local/share/supertuxkart/screenshots/'.
[info   ] [FileManager]: User-defined grand prix will be stored in '/home/user/.local/share/supertuxkart/grandprix/'.
[info   ] [FileManager]: Asset 0 will be loaded from '/usr/share/supertuxkart/data/challenges/'.
[info   ] [FileManager]: Asset 1 will be loaded from '/usr/share/supertuxkart/data/gfx/'.
[info   ] [FileManager]: Asset 2 will be loaded from '/usr/share/supertuxkart/data/grandprix/'.
[info   ] [FileManager]: Asset 3 will be loaded from '/usr/share/supertuxkart/data/gui/icons/'.
[info   ] [FileManager]: Asset 4 will be loaded from '/usr/share/supertuxkart/data/gui/screens/'.
[info   ] [FileManager]: Asset 5 will be loaded from '/usr/share/supertuxkart/data/gui/dialogs/'.
[info   ] [FileManager]: Asset 6 will be loaded from '/usr/share/supertuxkart/data/replay/'.
[info   ] [FileManager]: Asset 7 will be loaded from '/usr/share/supertuxkart/data/shaders/'.
[info   ] [FileManager]: Asset 8 will be loaded from '/usr/share/supertuxkart/data/skins/'.
[info   ] [FileManager]: Asset 9 will be loaded from '/usr/share/supertuxkart/data/ttf/'.
[info   ] [FileManager]: Asset 10 will be loaded from '/usr/share/supertuxkart/data/po/'.
[info   ] [FileManager]: Asset 11 will be loaded from '/usr/share/supertuxkart/data/library/'.
[info   ] [FileManager]: Asset 12 will be loaded from '/usr/share/supertuxkart/data/models/'.
[info   ] [FileManager]: Asset 13 will be loaded from '/usr/share/supertuxkart/data/music/'.
[info   ] [FileManager]: Asset 14 will be loaded from '/usr/share/supertuxkart/data/sfx/'.
[info   ] [FileManager]: Asset 15 will be loaded from '/usr/share/supertuxkart/data/textures/'.
[info   ] [FileManager]: Asset 16 will be loaded from '/usr/share/supertuxkart/data/tracks/'.
[verbose  ] translation: Env var LANGUAGE = 'fr_FR:fr'.
[verbose  ] translation: Language 'French (France)'.
[info   ] [IrrDriver Logger]: ..:: Antarctica Rendering Engine 2.0 ::..
[info   ] [IrrDriver Logger]: Compiled SDL Version 2.30.2
[info   ] [IrrDriver Logger]: Current SDL Version 2.30.2
[info   ] [IrrDriver Logger]: Using renderer: OpenGL 4.3.0
[info   ] [IrrDriver Logger]: Quadro M2200/PCIe/SSE2: NVIDIA Corporation
[info   ] [IrrDriver Logger]: OpenGL driver version is 1.2 or better.
[info   ] [IrrDriver Logger]: GLSL version: 4.3
[info   ] IrrDriver: OpenGL version: 4.3
[info   ] IrrDriver: OpenGL vendor: NVIDIA Corporation
[info   ] IrrDriver: OpenGL renderer: Quadro M2200/PCIe/SSE2
[info   ] IrrDriver: OpenGL version string: 4.3.0 NVIDIA 550.67
[info   ] IrrDriver: OpenGL total memory: 4096
[info   ] GLDriver: ARB Buffer Storage Present
[info   ] GLDriver: ARB Compute Shader Present
[info   ] GLDriver: ARB Arrays of Arrays Present
[info   ] GLDriver: ARB Texture Storage Present
[info   ] GLDriver: ARB Texture View Present
[info   ] GLDriver: ARB Image Load Store Present
[info   ] GLDriver: ARB Shader Atomic Counters Present
[info   ] GLDriver: ARB Shader Storage Buffer Object Present
[info   ] GLDriver: EXT Texture Compression S3TC Present
[info   ] GLDriver: ARB Uniform Buffer Object Present
[info   ] GLDriver: ARB Explicit Attrib Location Present
[info   ] GLDriver: EXT Texture Filter Anisotropic Present
[info   ] GLDriver: Geometry Shaders Present
[info   ] GLDriver: ARB Texture Buffer Object Present
[info   ] GLDriver: ARB Texture Swizzle Present
[info   ] GLDriver: ARB Pixel Buffer Object Present
[info   ] GLDriver: ARB Sampler Objects Present
[info   ] GLDriver: ARB Vertex Type 2_10_10_10_rev Present
[info   ] GLDriver: ARB Instanced Arrays Present
[info   ] SharedGPUObjects: Hardware Skinning enabled, method: TBO, max bones: 1024
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/screenquad.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/motion_blur.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/lightning.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/primitive2dlist.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/transparent.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/texturedquad.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/uniformcolortexturedquad.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/texturedquad.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/coloredquad.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/coloredquad.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/colortexturedquad.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/colortexturedquad.frag
[info   ] irr_driver: GLSL supported.
[info   ] GUI: Loading skin data from file: /usr/share/supertuxkart/data/skins/peach/stkskin.xml
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_pass.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_solid.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_shadow.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/white.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_skinning.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_skinning_shadow.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_normal_map.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_alpha_test.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_shadow_alpha_test.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_decal.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_grass_pass.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_grass.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_grass_shadow.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_unlit.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_transparent.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_ghost.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_dynamic_night_bloom.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_tilling_mitigation.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_vertical_mapping.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_road_blending.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_displace.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/colorize.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_normal_visualizer.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_normal_visualizer.geom
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sp_normal_visualizer.frag
[info   ] HTTPRequest: Sending userid=xxxxx&token=************************ to https://online.supertuxkart.net/api/v2/user/saved-session/
[info   ] HTTPRequest: Downloading https://online.supertuxkart.net/dl/xml/online_news.xml
[error  ] SFXBuffer: Positional audio is not supported with stereo files, but /usr/share/supertuxkart/data/sfx/WilhelmScream.ogg is stereo
[error  ] SFXBuffer: Positional audio is not supported with stereo files, but /usr/share/supertuxkart/data/sfx/car_revup.ogg is stereo
[info   ] addons: Using cached addons.xml.
[info   ] GrandPrixManager: Loading Grand Prix files from /usr/share/supertuxkart/data/grandprix/
[info   ] GrandPrixManager: Loading Grand Prix files from /home/valerie/.local/share/supertuxkart/grandprix/
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] KartModel: dl2502.spm has no striaght frame defined.
[warn   ] Material: Cannot determine texture full path: genericshadow.png
[warn   ] KartModel: p2000.spm has no striaght frame defined.
[warn   ] KartModel: p3400.spm has no striaght frame defined.
[info   ] Achievements: Synching achievement 1,2,3,4,5,6,7,8,9,10,11,12 to server.
[info   ] HTTPRequest: Sending userid=xxxxx&token=************************&achievementid=1%2C2%2C3%2C4%2C5%2C6%2C7%2C8%2C9%2C10%2C11%2C12 to https://online.supertuxkart.net/api/v2/user/achieving/
[info   ] HTTPRequest: Sending userid=xxxx&token=************************&visitingid=xxxx to https://online.supertuxkart.net/api/v2/user/get-friends-list/
[info   ] HTTPRequest: Sending userid=xxxx&token=************************ to https://online.supertuxkart.net/api/v2/user/poll/
[warn   ] LayoutManager: Statically sized widgets took all the place!!
[warn   ] LayoutManager: Statically sized widgets took all the place!!
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/simple_particle.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/simple_particle.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/alphatest_particle.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/alphatest_particle.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/degraded_ibl.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sunlight.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/pointlight.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/pointlight.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/linearizedepth.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/ssao.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/bilateralH.comp
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/bilateralV.comp
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/combine_diffuse_color.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/glow.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/tonemap.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/mlaa_color1.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/mlaa_blend2.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/mlaa_neigh3.frag
[warn   ] LayoutManager: Statically sized widgets took all the place!!
[warn   ] LayoutManager: Statically sized widgets took all the place!!
[warn   ] LayoutManager: Statically sized widgets took all the place!!
[warn   ] LayoutManager: Statically sized widgets took all the place!!
[warn   ] LayoutManager: Statically sized widgets took all the place!!
[warn   ] LayoutManager: Statically sized widgets took all the place!!
[warn   ] LayoutManager: Statically sized widgets took all the place!!
[warn   ] LayoutManager: Statically sized widgets took all the place!!
[warn   ] AbstractTopLevelContainer::addWidgetsRecursively: Widget target-type-spinner of type 1 has no dimensions
[warn   ] AbstractTopLevelContainer::addWidgetsRecursively: Widget target-type-text of type 5 has no dimensions
[warn   ] AbstractTopLevelContainer::addWidgetsRecursively: Widget ai-blue-spinner of type 1 has no dimensions
[warn   ] AbstractTopLevelContainer::addWidgetsRecursively: Widget ai-blue-text of type 5 has no dimensions
[verbose  ] RaceManager: Nb of karts=4, ghost karts:0 ai:3 players:1

[info   ] Track: Overall scene complexity estimated at 74
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/importance_sampling_specular.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/IBL.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sunlightshadow.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/pointlightscatter.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/gaussian6v.comp
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/gaussian6h.comp
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sky.vert
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/sky.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/dof.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/bloom.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/gaussian6h.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/bloomblend.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/lensblend.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/passthrough.frag
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] HTTPRequest: Downloading https://online.supertuxkart.net/api/v2/server/get-all/
[info   ] NetworkConfig: System is IPv4 only.
[info   ] ServerInfoDialog: Server id is xxxxx, owner is xxxxxx
[info   ] STKHost: Host initialized.
[info   ] ConnectToServer: SETUP
[info   ] ProtocolManager: A 15ConnectToServer protocol has been started.
[warn   ] STKHost: Failed to get enough stun servers using SRV record.
[info   ] ConnectToServer: Registering addr xxxxxxxxxxxxxxxxxx
[info   ] HTTPRequest: Sending userid=xxxxx&token=************************&server-id=xxxxxx&address=xxxxxxx&address-ipv6=&port=49114&aes-key=****************************&aes-iv=xxxxxx to https://online.supertuxkart.net/api/v2/server/join-server-key/
[info   ] ConnectToServer: Trying connecting to xxxxxxxxx from port xxxxxx, retry remain: 3
[info   ] ConnectToServer: Connected to xxxxxxxx
[info   ] ProtocolManager: A 11ClientLobby protocol has been started.
[info   ] ProtocolManager: A 15ConnectToServer protocol has been terminated.
[info   ] STKHost: Listening has been started.
[info   ] ClientLobby: Server will validate this online player.
[info   ] ClientLobby: Synchronous message of type 4
[info   ] ClientLobby: Synchronous message of type 6
[info   ] ClientLobby: Synchronous message of type 3
[info   ] ClientLobby: The server accepted the connection.
[info   ] ClientLobby: Synchronous message of type 17

[info   ] NetworkTimerSynchronizer: Network timer synchronized, difference: 1ms
[warn   ] LayoutManager: Statically sized widgets took all the place!!
[warn   ] LayoutManager: Widget 'continue' has a width of 0 (left_space = 0, fraction = 1.000000, max_width = )
[info   ] ClientLobby: Synchronous message of type 10
[info   ] LobbyProtocol: Player configuration ready.
[info   ] LobbyProtocol: Ready !
[verbose  ] RaceManager: Nb of karts=14, ghost karts:0 ai:0 players:14

[info   ] Track: Overall scene complexity estimated at 28
[info   ] NetworkPlayerController: New network player controller.
[info   ] NetworkPlayerController: New network player controller.
[info   ] NetworkPlayerController: New network player controller.
[info   ] NetworkPlayerController: New network player controller.
[info   ] NetworkPlayerController: New network player controller.
[info   ] NetworkPlayerController: New network player controller.
[info   ] NetworkPlayerController: New network player controller.
[info   ] NetworkPlayerController: New network player controller.
[info   ] NetworkPlayerController: New network player controller.
[info   ] NetworkPlayerController: New network player controller.
[info   ] NetworkPlayerController: New network player controller.
[info   ] NetworkPlayerController: New network player controller.
[info   ] NetworkPlayerController: New network player controller.
[info   ] ProtocolManager: A 12GameProtocol protocol has been started.
[info   ] ProtocolManager: A 18GameEventsProtocol protocol has been started.
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/godfade.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/gaussian3v.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/gaussian3h.frag
[info   ] ShaderFilesManager: Compiling shader: /usr/share/supertuxkart/data/shaders/godray.frag
[info   ] ClientLobby: Synchronous message of type 26
[info   ] ClientLobby: Live join started at 4061014.474000
Rewind [warn   ] RewindManager: Missing local state at ticks 26735

Thread 1 "supertuxkart" received signal SIGSEGV, Segmentation fault.
DrawCalls::parseSceneManager (this=this@entry=0x555556f1b5b0, List=..., 
    cam=cam@entry=0x555576d9e180)
    at /usr/src/debug/supertuxkart-git/stk-code/src/graphics/draw_calls.cpp:190
190	            node->updateAbsolutePosition();
```

Backtrace:
```
#0  DrawCalls::parseSceneManager (this=0x555556f1b5b0, 
    this@entry=<error reading variable: Cannot access memory at address 0x7fffffffdae8>, 
    List=..., 
    List@entry=<error reading variable: Cannot access memory at address 0x7fffffffdaf8>, 
    cam=0x555576d9e180, 
    cam@entry=<error reading variable: Cannot access memory at address 0x7fffffffdaf0>)
    at /usr/src/debug/supertuxkart-git/stk-code/src/graphics/draw_calls.cpp:190
#1  0x0000555555872e58 in DrawCalls::parseSceneManager (this=this@entry=0x555556f1b5b0, 
    List=<error reading variable: Cannot access memory at address 0x7fffffffdaa8>, 
    cam=cam@entry=0x555576d9e180)
    at /usr/src/debug/supertuxkart-git/stk-code/src/graphics/draw_calls.cpp:164
#2  0x000055555587316d in DrawCalls::prepareDrawCalls (this=0x555556f1b5b0, 
    camnode=0x555576d9e180)
    at /usr/src/debug/supertuxkart-git/stk-code/src/graphics/draw_calls.cpp:221
#3  0x00005555558c494a in ShaderBasedRenderer::renderSceneDeferred (this=0x555556f1b580, 
    camnode=0x555576d9e180, dt=0.0166666675, hasShadow=true, 
    forceRTT=<error reading variable: Cannot access memory at address 0x7fffffffdbf4>)
    at /usr/src/debug/supertuxkart-git/stk-code/src/graphics/shader_based_renderer.cpp:241
Backtrace stopped: Cannot access memory at address 0x7fffffffdd08
```

**Comment by deveee** [comment]
Should be fixed in https://github.com/supertuxkart/stk-code/commit/78c6f16d7985b4b5c3abc4168a530b645b7c4d40
